services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ML_SERVICE_URL=http://ml-service:8500
      - BACKEND_CORS_ORIGINS=http://localhost:8080,http://localhost:5500
    depends_on:
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - "8500:8500"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
