// ── STRIVER'S A2Z SHEET ────────────────────────────────────────────────────
//
// GENERATED by build_a2z.py from a2z-source.json — do not hand-edit; edit the
// generator or refresh the source instead.
//
// Provenance: a2z-source.json is the syllabus of the official sheet at
// takeuforward.org/prep-hub/strivers-a2z-dsa-sheet — 20 modules, 495 items,
// in the sheet's own order, with its section names and basic/core/pro tiers
// (shown as E/M/H). Every row is from the sheet; nothing is hand-authored.
//
// `learning:true` marks the sheet's lecture rows (theory, language basics,
// library tours). `traceable:false` means the row has no algorithm to
// visualise — the lecture rows and the 22 printing patterns — so the viewer
// shows a concept card. A lecture row can still be linked to a tracer in
// a2zTracers.js when one tells its story honestly.
//
// Ids are APPEND-ONLY: progress.js keys off them, so renumbering silently
// reassigns a student's completed work to a different problem. A row keeps
// the id it had on the previous sheet; the numeric prefix is therefore the
// module a row FIRST appeared in, not necessarily where it sits now.

const S = (step, title, official, problems) => ({ step, title, official, progress: 0, problems });

export const A2Z_STEPS = [
  S("Step 1", "Beginner Problems", 83, [
    // Fundamentals of Programming
    { id:"1-107", section:"Fundamentals of Programming", title:"Breaking The Myth", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-108", section:"Fundamentals of Programming", title:"Programming and What Are Computers?", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-109", section:"Fundamentals of Programming", title:"How to Think Like a Programmer", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-110", section:"Fundamentals of Programming", title:"Flowcharts and Pseudocode", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-111", section:"Fundamentals of Programming", title:"Flowchart Problem-Solving", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-112", section:"Fundamentals of Programming", title:"Dry Runs, Edge Cases and Debugging", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-113", section:"Fundamentals of Programming", title:"Programming Languages and Choosing a Path", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Language Basics
    { id:"1-114", section:"Language Basics", title:"Learn C++", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-115", section:"Language Basics", title:"Learn Java", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-116", section:"Language Basics", title:"Learn Python", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Logic Building (Patterns)
    { id:"1-81", section:"Logic Building (Patterns)", title:"Easy and Medium", difficulty:"M", viz:"array", world:"Step Through It", hook:"Watch it run, one step at a time.", traceable:false, learning:true },
    { id:"1-117", section:"Logic Building (Patterns)", title:"Hard", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false, learning:true },
    // Patterns
    { id:"1-82", section:"Patterns", title:"Pattern 1", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-83", section:"Patterns", title:"Pattern 2", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-84", section:"Patterns", title:"Pattern 3", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-85", section:"Patterns", title:"Pattern 4", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-86", section:"Patterns", title:"Pattern 5", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-87", section:"Patterns", title:"Pattern 6", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-88", section:"Patterns", title:"Pattern 7", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-89", section:"Patterns", title:"Pattern 8", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-90", section:"Patterns", title:"Pattern 9", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-91", section:"Patterns", title:"Pattern 10", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-92", section:"Patterns", title:"Pattern 11", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-93", section:"Patterns", title:"Pattern 12", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-94", section:"Patterns", title:"Pattern 13", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-95", section:"Patterns", title:"Pattern 14", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-96", section:"Patterns", title:"Pattern 15", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-97", section:"Patterns", title:"Pattern 16", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-98", section:"Patterns", title:"Pattern 17", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-99", section:"Patterns", title:"Pattern 18", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-100", section:"Patterns", title:"Pattern 19", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-101", section:"Patterns", title:"Pattern 20", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-102", section:"Patterns", title:"Pattern 21", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    { id:"1-103", section:"Patterns", title:"Pattern 22", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false },
    // Time Complexity
    { id:"1-80", section:"Time Complexity", title:"Theory with examples", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Standard Libraries & Collections
    { id:"1-104", section:"Standard Libraries & Collections", title:"STL", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-105", section:"Standard Libraries & Collections", title:"Java Collections", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-118", section:"Standard Libraries & Collections", title:"Python Libraries Part 1", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-119", section:"Standard Libraries & Collections", title:"Python Libraries Part 2", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Concept Basics
    { id:"1-120", section:"Concept Basics", title:"Basic Maths", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-121", section:"Concept Basics", title:"Basic Arrays", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-106", section:"Concept Basics", title:"Basic Hashing", difficulty:"E", viz:"votes", world:"Tally Board", hook:"Count once, look up instantly.", traceable:false, learning:true },
    { id:"1-122", section:"Concept Basics", title:"Basic String", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Basic Maths
    { id:"1-60", section:"Basic Maths", title:"Count all Digits of a Number", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-123", section:"Basic Maths", title:"Count number of odd digits in a number", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-12", section:"Basic Maths", title:"Reverse a number", difficulty:"M", viz:"mirror", world:"Mirror Writing", hook:"Build the answer backwards as you strip the input." },
    { id:"1-61", section:"Basic Maths", title:"Palindrome Number", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-124", section:"Basic Maths", title:"Return the Largest Digit in a Number", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-67", section:"Basic Maths", title:"Factorial of a given number", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-63", section:"Basic Maths", title:"Check if the Number is Armstrong", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-125", section:"Basic Maths", title:"Check for Perfect Number", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-64", section:"Basic Maths", title:"Check for Prime Number", difficulty:"M", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-126", section:"Basic Maths", title:"Count of Prime Numbers till N", difficulty:"E", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-62", section:"Basic Maths", title:"GCD of Two Numbers", difficulty:"M", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"1-127", section:"Basic Maths", title:"LCM of two numbers", difficulty:"M", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"8-31", section:"Basic Maths", title:"Divisors of a Number", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    // Basic Arrays
    { id:"1-128", section:"Basic Arrays", title:"Sum of Array Elements", difficulty:"E", viz:"array", world:"Row of Boxes", hook:"A line of boxes, each with an address." },
    { id:"1-129", section:"Basic Arrays", title:"Count of odd numbers in Array", difficulty:"E", viz:"array", world:"Row of Boxes", hook:"A line of boxes, each with an address." },
    { id:"3-3", section:"Basic Arrays", title:"Check if the Array is Sorted I", difficulty:"E", viz:"array", world:"Queue Inspection", hook:"One out-of-order pair is enough to fail." },
    { id:"1-23", section:"Basic Arrays", title:"Reverse an array", difficulty:"E", viz:"mirror", world:"Reversing a Queue", hook:"Two pointers walking inward, recursively." },
    // Basic Hashing
    { id:"1-71", section:"Basic Hashing", title:"Highest Occurring Element in an Array", difficulty:"M", viz:"votes", world:"Tally Board", hook:"Count once, look up instantly." },
    { id:"1-130", section:"Basic Hashing", title:"Second Highest Occurring Element", difficulty:"M", viz:"votes", world:"Tally Board", hook:"Count once, look up instantly." },
    { id:"1-131", section:"Basic Hashing", title:"Sum of Highest and Lowest Frequency", difficulty:"M", viz:"votes", world:"Tally Board", hook:"Count once, look up instantly." },
    // Basic Strings
    { id:"1-132", section:"Basic Strings", title:"Reverse a String II", difficulty:"E", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"1-68", section:"Basic Strings", title:"Palindrome Check", difficulty:"M", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"5-3", section:"Basic Strings", title:"Largest Odd Number in a String", difficulty:"M", viz:"dna", world:"Trimming Digits", hook:"Scan from the right for the first odd digit." },
    { id:"5-4", section:"Basic Strings", title:"Longest Common Prefix", difficulty:"M", viz:"trie", world:"Shared Road", hook:"Walk together until the paths diverge." },
    { id:"5-17", section:"Basic Strings", title:"Isomorphic Strings", difficulty:"E", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"5-6", section:"Basic Strings", title:"Rotate String", difficulty:"M", viz:"carousel", world:"Rotating Dial", hook:"Any rotation is a substring of the doubled string." },
    { id:"5-18", section:"Basic Strings", title:"Valid Anagram", difficulty:"E", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"5-8", section:"Basic Strings", title:"Sort Characters by Frequency", difficulty:"M", viz:"leaderboard", world:"Popularity Chart", hook:"Count, then sort the counts." },
    // Basic Recursion
    { id:"1-133", section:"Basic Recursion", title:"Recursion Theory", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"1-134", section:"Basic Recursion", title:"Recursion Concepts with Parameters", difficulty:"M", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop.", traceable:false, learning:true },
    { id:"1-21", section:"Basic Recursion", title:"Sum of First N Numbers", difficulty:"E", viz:"fractal", world:"Stacking Coins", hook:"Parameterised versus functional recursion." },
    { id:"1-135", section:"Basic Recursion", title:"Factorial of a Given Number", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-136", section:"Basic Recursion", title:"Sum of Array Elements II", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-137", section:"Basic Recursion", title:"Reverse a String I", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-138", section:"Basic Recursion", title:"Check if String is Palindrome or Not", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-139", section:"Basic Recursion", title:"Check if a Number is Prime or Not", difficulty:"M", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-140", section:"Basic Recursion", title:"Reverse an array 2", difficulty:"M", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-141", section:"Basic Recursion", title:"Check if the Array is Sorted II", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-142", section:"Basic Recursion", title:"Sum of Digits in a Given Number", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function calling itself needs a way to stop." },
    { id:"1-25", section:"Basic Recursion", title:"Fibonacci Number", difficulty:"M", viz:"fractal", world:"Rabbit Pairs", hook:"The call tree explodes — this is why memoisation exists." },
  ]),
  S("Step 2", "Sorting", 7, [
    // Algorithms
    { id:"2-1", section:"Algorithms", title:"Selection Sort", difficulty:"M", viz:"leaderboard", world:"Leaderboard Selection", hook:"Find the champion, move them to the top. Repeat." },
    { id:"2-2", section:"Algorithms", title:"Bubble Sort", difficulty:"M", viz:"bubbles", world:"Bubble Tea Queue", hook:"Heavy bubbles sink; light ones rise." },
    { id:"2-8", section:"Algorithms", title:"Insertion Sorting", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"2-9", section:"Algorithms", title:"Merge Sorting", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"2-10", section:"Algorithms", title:"Quick Sorting", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"2-5", section:"Algorithms", title:"Recursive Bubble Sort", difficulty:"M", viz:"bubbles", world:"Bubble Tea Queue", hook:"The same passes, expressed as recursion." },
    { id:"2-6", section:"Algorithms", title:"Recursive Insertion Sort", difficulty:"M", viz:"cards", world:"Sorting Playing Cards", hook:"Sort the first n-1, then place the last." },
  ]),
  S("Step 3", "Arrays", 32, [
    // Fundamentals
    { id:"3-8", section:"Fundamentals", title:"Linear Search", difficulty:"E", viz:"searchbeam", world:"Door-to-Door", hook:"The baseline every faster search is measured against." },
    { id:"3-1", section:"Fundamentals", title:"Largest Element", difficulty:"E", viz:"leaderboard", world:"Tallest in the Room", hook:"One pass, one running champion." },
    { id:"3-2", section:"Fundamentals", title:"Second Largest Element", difficulty:"E", viz:"podium", world:"Silver Medal", hook:"Two runners-up tracked in a single sweep." },
    { id:"3-12", section:"Fundamentals", title:"Maximum Consecutive Ones", difficulty:"E", viz:"array", world:"Winning Streak", hook:"Reset the counter the moment the streak breaks." },
    { id:"3-5", section:"Fundamentals", title:"Left Rotate Array by One", difficulty:"E", viz:"carousel", world:"Carousel", hook:"Everyone shifts one seat; the first wraps around." },
    { id:"3-6", section:"Fundamentals", title:"Left Rotate Array by K Places", difficulty:"M", viz:"carousel", world:"Carousel", hook:"Three reversals beat K separate shifts." },
    // Logic Building
    { id:"3-7", section:"Logic Building", title:"Move Zeros to End", difficulty:"E", viz:"conveyor", world:"Sorting Belt", hook:"Keep order for the rest while zeros sink." },
    { id:"3-4", section:"Logic Building", title:"Remove duplicates from sorted array", difficulty:"E", viz:"dedup", world:"Guest List Cleanup", hook:"A write pointer trailing a read pointer." },
    { id:"3-11", section:"Logic Building", title:"Find missing number", difficulty:"E", viz:"seats", world:"Empty Seat", hook:"XOR or sum — both beat sorting." },
    { id:"3-9", section:"Logic Building", title:"Union of two sorted arrays", difficulty:"M", viz:"venn", world:"Merging Guest Lists", hook:"Two pointers, no duplicates." },
    { id:"3-10", section:"Logic Building", title:"Intersection of two sorted arrays", difficulty:"M", viz:"venn", world:"Mutual Friends", hook:"Advance whichever side is behind." },
    // FAQs(Medium)
    { id:"3-18", section:"FAQs(Medium)", title:"Majority Element-I", difficulty:"M", viz:"votes", world:"Landslide Vote", hook:"Boyer-Moore: cancel opposing votes until one survives." },
    { id:"3-24", section:"FAQs(Medium)", title:"Leaders in an Array", difficulty:"M", viz:"mountain", world:"Mountain Peaks", hook:"Scan from the right and keep the running maximum." },
    { id:"3-22", section:"FAQs(Medium)", title:"Rearrange array elements by sign", difficulty:"M", viz:"twopointers", world:"Alternating Teams", hook:"Two write cursors, one for each sign." },
    { id:"3-28", section:"FAQs(Medium)", title:"Print the matrix in spiral manner", difficulty:"M", viz:"grid", world:"Peeling an Onion", hook:"Four shrinking boundaries, walked in turn." },
    { id:"3-42", section:"FAQs(Medium)", title:"Pascal's Triangle I", difficulty:"M", viz:"array", world:"Row of Boxes", hook:"A line of boxes, each with an address." },
    { id:"3-43", section:"FAQs(Medium)", title:"Pascal's Triangle II", difficulty:"M", viz:"array", world:"Row of Boxes", hook:"A line of boxes, each with an address." },
    { id:"3-30", section:"FAQs(Medium)", title:"Pascal's Triangle III", difficulty:"M", viz:"fractal", world:"Stacked Bricks", hook:"Each brick is the sum of the two beneath it." },
    { id:"3-27", section:"FAQs(Medium)", title:"Rotate matrix by 90 degrees", difficulty:"M", viz:"grid", world:"Turning a Photo", hook:"Transpose, then reverse each row." },
    { id:"3-26", section:"FAQs(Medium)", title:"Set Matrix Zeroes", difficulty:"M", viz:"grid", world:"Spreadsheet Wipe", hook:"Use row 0 and column 0 as your own bookkeeping." },
    { id:"3-16", section:"FAQs(Medium)", title:"Two Sum", difficulty:"E", viz:"twopointers", world:"Shopping Budget", hook:"Hash what you've seen, not what's coming." },
    { id:"3-32", section:"FAQs(Medium)", title:"3 Sum", difficulty:"M", viz:"twopointers", world:"Three-Way Split", hook:"Fix one, two-pointer the rest — sorting makes it work." },
    { id:"3-33", section:"FAQs(Medium)", title:"4 Sum", difficulty:"H", viz:"twopointers", world:"Four-Way Split", hook:"The same idea nested one level deeper." },
    { id:"3-17", section:"FAQs(Medium)", title:"Sort an array of 0's 1's and 2's", difficulty:"M", viz:"sorting", world:"Dutch National Flag", hook:"Three pointers sort three values in one pass." },
    { id:"3-19", section:"FAQs(Medium)", title:"Kadane's Algorithm", difficulty:"M", viz:"stockchart", world:"Best Trading Streak", hook:"Extend the run, or cut your losses." },
    { id:"3-23", section:"FAQs(Medium)", title:"Next Permutation", difficulty:"M", viz:"sorting", world:"Dictionary Order", hook:"Find the pivot, swap the smallest bigger, reverse the tail." },
    // FAQs(Hard)
    { id:"3-31", section:"FAQs(Hard)", title:"Majority Element-II", difficulty:"M", viz:"votes", world:"Three-Way Race", hook:"At most two candidates can clear a third of the vote." },
    { id:"3-38", section:"FAQs(Hard)", title:"Find the repeating and missing number", difficulty:"M", viz:"seats", world:"Duplicate Ticket", hook:"Two equations, two unknowns." },
    { id:"3-39", section:"FAQs(Hard)", title:"Count Inversions", difficulty:"H", viz:"mergesort", world:"Measuring Disorder", hook:"Merge sort counts them for free while it merges." },
    { id:"3-40", section:"FAQs(Hard)", title:"Reverse Pairs", difficulty:"H", viz:"mergesort", world:"Steep Drops", hook:"A second scan inside the merge, same O(n log n)." },
    { id:"3-41", section:"FAQs(Hard)", title:"Maximum Product Subarray in an Array", difficulty:"M", viz:"stockchart", world:"Compounding Returns", hook:"A negative can become the best — track min and max." },
    { id:"3-37", section:"FAQs(Hard)", title:"Merge two sorted arrays without extra space", difficulty:"M", viz:"mergesort", world:"Two Shelves, One Order", hook:"The gap method, or a careful backward walk." },
  ]),
  S("Step 4", "Hashing", 6, [
    // Theory
    { id:"4-51", section:"Theory", title:"Basic Hashing", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // FAQs
    { id:"3-25", section:"FAQs", title:"Longest Consecutive Sequence in an Array", difficulty:"M", viz:"train", world:"Rebuilding a Chain", hook:"Only start counting from a true sequence head." },
    { id:"3-15", section:"FAQs", title:"Longest subarray with sum K", difficulty:"M", viz:"stockchart", world:"Ledger Balance", hook:"Prefix sums in a map — the window trick breaks here." },
    { id:"3-34", section:"FAQs", title:"Largest Subarray with Sum 0", difficulty:"M", viz:"stockchart", world:"Break-Even Streak", hook:"A repeated prefix sum means the gap sums to zero." },
    { id:"3-29", section:"FAQs", title:"Count subarrays with given sum", difficulty:"M", viz:"stockchart", world:"Ledger Audit", hook:"Every prefix you've seen is a potential left edge." },
    { id:"3-35", section:"FAQs", title:"Count subarrays with given xor K", difficulty:"H", viz:"circuit", world:"Parity Check", hook:"Prefix XOR behaves exactly like prefix sum." },
  ]),
  S("Step 5", "Binary Search", 32, [
    // Fundamentals
    { id:"4-33", section:"Fundamentals", title:"Search X in sorted array", difficulty:"E", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-2", section:"Fundamentals", title:"Lower Bound", difficulty:"M", viz:"binarysearch", world:"First Fit", hook:"The first index not less than the target." },
    { id:"4-3", section:"Fundamentals", title:"Upper Bound", difficulty:"M", viz:"binarysearch", world:"Just Past It", hook:"The first index strictly greater." },
    // Logic Building
    { id:"4-4", section:"Logic Building", title:"Search insert position", difficulty:"E", viz:"binarysearch", world:"Shelving a Book", hook:"Where it would go if it isn't already there." },
    { id:"4-5", section:"Logic Building", title:"Floor and Ceil in Sorted Array", difficulty:"M", viz:"binarysearch", world:"Nearest Neighbours", hook:"The closest value on each side." },
    { id:"4-6", section:"Logic Building", title:"First and last occurrence", difficulty:"M", viz:"binarysearch", world:"Edges of a Block", hook:"Two biased searches instead of one." },
    { id:"4-35", section:"Logic Building", title:"Search in rotated sorted array-I", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-36", section:"Logic Building", title:"Search in rotated sorted array-II", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-37", section:"Logic Building", title:"Find minimum in Rotated Sorted Array", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-38", section:"Logic Building", title:"Find out how many times the array is rotated", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-39", section:"Logic Building", title:"Single element in sorted array", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-34", section:"Logic Building", title:"Count Occurrences in a Sorted Array", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    // On answers
    { id:"4-40", section:"On answers", title:"Find square root of a number", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-41", section:"On answers", title:"Find Nth root of a number", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-18", section:"On answers", title:"Find the smallest divisor", difficulty:"M", viz:"binarysearch", world:"Choosing a Divisor", hook:"Bigger divisor, smaller sum — monotonic again." },
    { id:"4-16", section:"On answers", title:"Koko eating bananas", difficulty:"H", viz:"binarysearch", world:"Eating Rate", hook:"Feasibility is monotonic — that is what makes it searchable." },
    { id:"4-17", section:"On answers", title:"Minimum days to make M bouquets", difficulty:"H", viz:"binarysearch", world:"Blooming Garden", hook:"Search the day; check feasibility linearly." },
    { id:"4-42", section:"On answers", title:"Capacity to Ship Packages Within D Days", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-20", section:"On answers", title:"Kth Missing Positive Number", difficulty:"H", viz:"seats", world:"Missing Tickets", hook:"Missing count at an index is a searchable function." },
    { id:"4-24", section:"On answers", title:"Painter's Partition", difficulty:"H", viz:"binarysearch", world:"Painting a Fence", hook:"The same minimise-the-maximum shape again." },
    // FAQs
    { id:"4-21", section:"FAQs", title:"Aggressive Cows", difficulty:"H", viz:"canyon", world:"Spacing the Stalls", hook:"Maximise the minimum gap." },
    { id:"4-22", section:"FAQs", title:"Book Allocation Problem", difficulty:"H", viz:"binarysearch", world:"Dividing the Reading", hook:"Minimise the largest share." },
    { id:"4-13", section:"FAQs", title:"Find peak element", difficulty:"M", viz:"mountain", world:"Hill Climbing", hook:"Walk uphill — a peak must exist that way." },
    { id:"4-45", section:"FAQs", title:"Median of 2 sorted arrays", difficulty:"H", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-46", section:"FAQs", title:"Kth element of 2 sorted arrays", difficulty:"H", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"4-44", section:"FAQs", title:"Minimize Max Distance to Gas Station", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-43", section:"FAQs", title:"Split array - largest sum", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    // 2D Arrays
    { id:"4-47", section:"2D Arrays", title:"Find row with maximum 1's", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-29", section:"2D Arrays", title:"Search in a 2D Matrix", difficulty:"M", viz:"grid", world:"Flattened Grid", hook:"Treat the matrix as one long sorted array." },
    { id:"4-48", section:"2D Arrays", title:"Search in 2D matrix - II", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-49", section:"2D Arrays", title:"Find Peak Element - II", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"4-50", section:"2D Arrays", title:"Matrix Median", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
  ]),
  S("Step 6", "Strings (Basic and Medium)", 7, [
    // Parentheses
    { id:"5-1", section:"Parentheses", title:"Remove Outermost Parentheses", difficulty:"M", viz:"stackviz", world:"Nested Boxes", hook:"Depth tells you which brackets are decoration." },
    { id:"5-19", section:"Parentheses", title:"Maximum Nesting Depth of the Parentheses", difficulty:"M", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    // String Conversions
    { id:"5-10", section:"String Conversions", title:"Roman to Integer", difficulty:"E", viz:"terminal", world:"Roman Numerals", hook:"A smaller value before a bigger one subtracts." },
    { id:"5-20", section:"String Conversions", title:"String to Integer (atoi)", difficulty:"M", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    // Substring Problems
    { id:"6-61", section:"Substring Problems", title:"Count Number of Substrings", difficulty:"E", viz:"bst", world:"Filing Cabinet", hook:"Left is smaller, right is bigger — always.", traceable:false, learning:true },
    { id:"5-14", section:"Substring Problems", title:"Longest Palindromic Substring", difficulty:"M", viz:"mirror", world:"Mirror Centre", hook:"Expand around every centre — 2n-1 of them." },
    { id:"5-15", section:"Substring Problems", title:"Sum of Beauty of All Substrings", difficulty:"M", viz:"votes", world:"Letter Tally", hook:"Maintain frequencies as the window grows." },
  ]),
  S("Step 7", "Recursion", 22, [
    // Implementation Problems
    { id:"7-2", section:"Implementation Problems", title:"Pow(x,n)", difficulty:"M", viz:"fractal", world:"Fast Exponentiation", hook:"Halve the exponent, square the result." },
    { id:"7-7", section:"Implementation Problems", title:"Generate Parentheses", difficulty:"M", viz:"backtrack", world:"Balanced Brackets", hook:"Prune the moment the string can't be balanced." },
    { id:"7-28", section:"Implementation Problems", title:"Power Set", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-3", section:"Implementation Problems", title:"Count Good Numbers", difficulty:"M", viz:"fractal", world:"Counting Patterns", hook:"Fast power under a modulus." },
    { id:"7-26", section:"Implementation Problems", title:"Reverse a Stack", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    // Subsequence Pattern Problems
    { id:"7-34", section:"Subsequence Pattern Problems", title:"Learn All Patterns of Subsequences (Theory)", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false, learning:true },
    { id:"7-30", section:"Subsequence Pattern Problems", title:"Check if there exists a subsequence with sum K", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-29", section:"Subsequence Pattern Problems", title:"Count all subsequences with sum K", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-27", section:"Subsequence Pattern Problems", title:"Generate Binary Strings Without Consecutive 1s", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    // FAQs (Medium)
    { id:"7-11", section:"FAQs (Medium)", title:"Combination Sum", difficulty:"M", viz:"backtrack", world:"Making Change", hook:"Reuse allowed — don't advance the index." },
    { id:"7-12", section:"FAQs (Medium)", title:"Combination Sum II", difficulty:"M", viz:"backtrack", world:"Making Change", hook:"Skip duplicates at the same depth." },
    { id:"7-31", section:"FAQs (Medium)", title:"Subsets I", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-32", section:"FAQs (Medium)", title:"Subsets II", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-15", section:"FAQs (Medium)", title:"Combination Sum III", difficulty:"H", viz:"backtrack", world:"Fixed-Size Pick", hook:"Two constraints to prune against." },
    // Hard
    { id:"7-16", section:"Hard", title:"Letter Combinations of a Phone Number", difficulty:"H", viz:"backtrack", world:"Old Keypad", hook:"A branch per letter on each key." },
    // FAQs (Hard)
    { id:"7-17", section:"FAQs (Hard)", title:"Palindrome partitioning", difficulty:"H", viz:"backtrack", world:"Cutting a String", hook:"Cut only where the left piece is a palindrome." },
    { id:"7-18", section:"FAQs (Hard)", title:"Word Search", difficulty:"H", viz:"maze", world:"Word Grid", hook:"Mark visited, recurse, then unmark." },
    { id:"7-33", section:"FAQs (Hard)", title:"N Queen", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"7-20", section:"FAQs (Hard)", title:"Rat in a Maze", difficulty:"H", viz:"maze", world:"Maze Escape", hook:"Four directions, one visited set." },
    { id:"7-22", section:"FAQs (Hard)", title:"M Coloring Problem", difficulty:"H", viz:"graphs", world:"Map Colouring", hook:"Check neighbours before committing a colour." },
    { id:"7-23", section:"FAQs (Hard)", title:"Sudoku Solver", difficulty:"H", viz:"grid", world:"Sudoku", hook:"Constraint propagation plus backtracking." },
    { id:"7-24", section:"FAQs (Hard)", title:"Expression Add Operators", difficulty:"H", viz:"backtrack", world:"Building Equations", hook:"Multiplication forces you to track the last operand." },
  ]),
  S("Step 8", "Linked-List", 49, [
    // Fundamentals (Single LL)
    { id:"6-59", section:"Fundamentals (Single LL)", title:"Introduction to Singly LinkedList", difficulty:"E", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"8-36", section:"Fundamentals (Single LL)", title:"Traversal in Linked List", difficulty:"E", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-37", section:"Fundamentals (Single LL)", title:"Deletion in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"8-38", section:"Fundamentals (Single LL)", title:"Insertion in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"6-31", section:"Fundamentals (Single LL)", title:"Deletion of the head of LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-39", section:"Fundamentals (Single LL)", title:"Deletion of the tail of Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-40", section:"Fundamentals (Single LL)", title:"Deletion of the Kth element of Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-41", section:"Fundamentals (Single LL)", title:"Delete the element with value X", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-30", section:"Fundamentals (Single LL)", title:"Insertion at the head of Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-42", section:"Fundamentals (Single LL)", title:"Insertion at the tail of Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-43", section:"Fundamentals (Single LL)", title:"Insertion at the Kth position of Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-44", section:"Fundamentals (Single LL)", title:"Insertion before the value X in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-32", section:"Fundamentals (Single LL)", title:"Find the length of the Linked List", difficulty:"E", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-33", section:"Fundamentals (Single LL)", title:"Search in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    // Fundamentals (Doubly LL)
    { id:"6-60", section:"Fundamentals (Doubly LL)", title:"Introduction to Doubly LL", difficulty:"E", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"8-45", section:"Fundamentals (Doubly LL)", title:"Deletion in Doubly LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"8-46", section:"Fundamentals (Doubly LL)", title:"Insertion in DLL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next.", traceable:false, learning:true },
    { id:"8-47", section:"Fundamentals (Doubly LL)", title:"Convert Array to Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-48", section:"Fundamentals (Doubly LL)", title:"Delete Tail of Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-49", section:"Fundamentals (Doubly LL)", title:"Delete Kth Element of Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-50", section:"Fundamentals (Doubly LL)", title:"Removing given node in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-35", section:"Fundamentals (Doubly LL)", title:"Insert node before head in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-51", section:"Fundamentals (Doubly LL)", title:"Insert node before tail in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-52", section:"Fundamentals (Doubly LL)", title:"Insert node before (kth node) in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-53", section:"Fundamentals (Doubly LL)", title:"Insert before given node in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-36", section:"Fundamentals (Doubly LL)", title:"Delete head of Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-9", section:"Fundamentals (Doubly LL)", title:"Reverse a Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Turning the Train", hook:"Swap prev and next at every node." },
    // Logic Building
    { id:"6-51", section:"Logic Building", title:"Add two numbers in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-44", section:"Logic Building", title:"Segregate odd and even nodes in Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-48", section:"Logic Building", title:"Sort a Linked List of 0's 1's and 2's", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"6-45", section:"Logic Building", title:"Remove Nth node from the back of the LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-39", section:"Logic Building", title:"Reverse a LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    // FAQs (Medium)
    { id:"6-50", section:"FAQs (Medium)", title:"Add one to a number represented by LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-37", section:"FAQs (Medium)", title:"Find Middle of Linked List", difficulty:"E", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-46", section:"FAQs (Medium)", title:"Delete the middle node in LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-43", section:"FAQs (Medium)", title:"Check if LL is palindrome or not", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-49", section:"FAQs (Medium)", title:"Find the intersection point of Y LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-40", section:"FAQs (Medium)", title:"Detect a loop in LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-41", section:"FAQs (Medium)", title:"Find the starting point in LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-42", section:"FAQs (Medium)", title:"Length of loop in LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    // FAQs (Hard)
    { id:"6-55", section:"FAQs (Hard)", title:"Reverse LL in group of given size K", difficulty:"H", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-56", section:"FAQs (Hard)", title:"Rotate a LL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"8-54", section:"FAQs (Hard)", title:"Merge two Sorted Lists", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"6-57", section:"FAQs (Hard)", title:"Flattening of LL", difficulty:"H", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-47", section:"FAQs (Hard)", title:"Sort LL", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"6-58", section:"FAQs (Hard)", title:"Clone a LL with random and next pointer", difficulty:"H", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    // FAQS (DLL)
    { id:"6-52", section:"FAQS (DLL)", title:"Delete all occurrences of a key in DLL", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"6-54", section:"FAQS (DLL)", title:"Remove duplicates from sorted DLL", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"6-53", section:"FAQS (DLL)", title:"Find Pairs with Given Sum in Doubly Linked List", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
  ]),
  S("Step 9", "Bit Manipulation", 14, [
    // Theory
    { id:"8-35", section:"Theory", title:"Introduction to Bits and Tricks", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches.", traceable:false, learning:true },
    // Bit Fundamentals
    { id:"8-19", section:"Bit Fundamentals", title:"Check if the i-th bit is Set or Not", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-20", section:"Bit Fundamentals", title:"Check if a Number is Odd or Not", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-21", section:"Bit Fundamentals", title:"Check if a Number is Power of 2 or Not", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-22", section:"Bit Fundamentals", title:"Count the Number of Set Bits", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"9-41", section:"Bit Fundamentals", title:"Set/Unset the rightmost unset bit", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches.", traceable:false, learning:true },
    { id:"8-23", section:"Bit Fundamentals", title:"Swap Two Numbers", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    // Problems
    { id:"8-25", section:"Problems", title:"Minimum Bit Flips to Convert Number", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-26", section:"Problems", title:"Single Number - I", difficulty:"E", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"9-42", section:"Problems", title:"Single Number - II", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-29", section:"Problems", title:"Single Number - III", difficulty:"H", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-24", section:"Problems", title:"Divide two numbers without multiplication and division", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-27", section:"Problems", title:"Power Set Bit Manipulation", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-28", section:"Problems", title:"XOR of numbers in a given range", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
  ]),
  S("Step 10", "Greedy Algorithms", 14, [
    // Easy
    { id:"12-1", section:"Easy", title:"Assign Cookies", difficulty:"M", viz:"balance", world:"Matching Sizes", hook:"Sort both sides and pair greedily." },
    { id:"12-4", section:"Easy", title:"Lemonade Change", difficulty:"M", viz:"vault", world:"Making Change", hook:"Spend the largest notes you can afford to." },
    { id:"12-2", section:"Easy", title:"Fractional Knapsack", difficulty:"M", viz:"vault", world:"Loading a Truck", hook:"Best value-per-weight first — fractions make greedy safe." },
    { id:"12-17", section:"Easy", title:"Jump Game - I", difficulty:"M", viz:"timeline", world:"Booking the Day", hook:"Take the locally best and never look back." },
    // Scheduling and Interval Problems
    { id:"12-12", section:"Scheduling and Interval Problems", title:"Shortest Job First", difficulty:"M", viz:"timeline", world:"CPU Scheduling", hook:"Shortest first minimises average wait." },
    { id:"12-10", section:"Scheduling and Interval Problems", title:"Job sequencing Problem", difficulty:"M", viz:"timeline", world:"Deadline Scheduling", hook:"Place each job as late as its deadline allows." },
    { id:"12-6", section:"Scheduling and Interval Problems", title:"N meetings in one room", difficulty:"M", viz:"timeline", world:"Room Booking", hook:"Sort by finish time, not start time." },
    { id:"12-15", section:"Scheduling and Interval Problems", title:"Non-overlapping Intervals", difficulty:"M", viz:"timeline", world:"Dropping Conflicts", hook:"Keep the most meetings by ending earliest." },
    { id:"12-13", section:"Scheduling and Interval Problems", title:"Insert Interval", difficulty:"M", viz:"timeline", world:"Calendar Insert", hook:"Three phases: before, overlapping, after." },
    { id:"12-14", section:"Scheduling and Interval Problems", title:"Merge Intervals", difficulty:"M", viz:"timeline", world:"Calendar Merge", hook:"Sort by start and the overlaps fall out in one pass." },
    { id:"12-18", section:"Scheduling and Interval Problems", title:"Minimum number of platforms required for a railway", difficulty:"M", viz:"timeline", world:"Booking the Day", hook:"Take the locally best and never look back." },
    // Hard
    { id:"12-16", section:"Hard", title:"Valid Paranthesis Checker", difficulty:"H", viz:"timeline", world:"Booking the Day", hook:"Take the locally best and never look back." },
    { id:"12-11", section:"Hard", title:"Candy", difficulty:"H", viz:"leaderboard", world:"Fair Rewards", hook:"Two passes — left to right, then right to left." },
    { id:"12-8", section:"Hard", title:"Jump Game II", difficulty:"H", viz:"canyon", world:"Crossing Gaps", hook:"Jump only when the current range runs out." },
  ]),
  S("Step 11", "Sliding Window / 2 Pointer", 13, [
    // Pattern and Template
    { id:"11-29", section:"Pattern and Template", title:"Theory", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false, learning:true },
    // Constant Window
    { id:"10-8", section:"Constant Window", title:"Maximum Points You Can Obtain from Cards", difficulty:"M", viz:"cards", world:"Cards from Both Ends", hook:"A fixed window on the wrap-around." },
    // Longest and Smallest Window Problems
    { id:"10-1", section:"Longest and Smallest Window Problems", title:"Longest Substring Without Repeating Characters", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"Shrink from the left the moment a repeat appears." },
    { id:"10-2", section:"Longest and Smallest Window Problems", title:"Max Consecutive Ones III", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"The window is valid while flips used ≤ k." },
    { id:"10-3", section:"Longest and Smallest Window Problems", title:"Fruit Into Baskets", difficulty:"M", viz:"windowslide", world:"Two Baskets", hook:"At most two distinct kinds in the window." },
    { id:"10-9", section:"Longest and Smallest Window Problems", title:"Longest Substring With At Most K Distinct Characters", difficulty:"H", viz:"windowslide", world:"Sliding Window", hook:"A frequency map decides when to shrink." },
    { id:"10-4", section:"Longest and Smallest Window Problems", title:"Longest Repeating Character Replacement", difficulty:"H", viz:"windowslide", world:"Sliding Window", hook:"Window length minus the most frequent letter." },
    { id:"10-11", section:"Longest and Smallest Window Problems", title:"Minimum Window Substring", difficulty:"H", viz:"windowslide", world:"Shrinking Window", hook:"Expand until valid, then shrink while it stays valid." },
    { id:"10-12", section:"Longest and Smallest Window Problems", title:"Minimum Window Subsequence", difficulty:"H", viz:"windowslide", world:"Shrinking Window", hook:"Order matters here — not just membership." },
    // Counting Subarrays / Substrings Problems
    { id:"10-7", section:"Counting Subarrays / Substrings Problems", title:"Number of Substrings Containing All Three Characters", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"Count by last-seen positions." },
    { id:"10-5", section:"Counting Subarrays / Substrings Problems", title:"Binary Subarrays With Sum", difficulty:"M", viz:"windowslide", world:"Window Counting", hook:"Exactly-k as a difference of two at-most-k runs." },
    { id:"10-13", section:"Counting Subarrays / Substrings Problems", title:"Count number of Nice subarrays", difficulty:"H", viz:"windowslide", world:"Sliding Window", hook:"Grow right, shrink left, never recount." },
    { id:"10-10", section:"Counting Subarrays / Substrings Problems", title:"Subarrays with K Different Integers", difficulty:"H", viz:"windowslide", world:"Window Counting", hook:"The at-most-k difference trick again." },
  ]),
  S("Step 12", "Stack / Queues", 31, [
    // Implementation
    { id:"12-20", section:"Implementation", title:"Implementation using different DS", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open.", traceable:false, learning:true },
    { id:"9-29", section:"Implementation", title:"Implement Stack using Arrays", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-30", section:"Implementation", title:"Implement Queue using Arrays", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-3", section:"Implementation", title:"Implement Stack using Queue", difficulty:"M", viz:"stackviz", world:"Reversing a Line", hook:"Rotate the queue after every push." },
    { id:"9-4", section:"Implementation", title:"Implement Queue using Stack", difficulty:"M", viz:"stackviz", world:"Two Plate Stacks", hook:"Amortised O(1) — each item moves at most twice." },
    { id:"9-31", section:"Implementation", title:"Implement stack using Linkedlist", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"9-32", section:"Implementation", title:"Implement queue using Linkedlist", difficulty:"M", viz:"linkedlist", world:"Train Carriages", hook:"Each carriage knows only the next." },
    { id:"9-33", section:"Implementation", title:"Balanced Paranthesis", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    // Prefix, Infix and Postfix Conversions
    { id:"9-9", section:"Prefix, Infix and Postfix Conversions", title:"Infix to Postfix Conversion", difficulty:"M", viz:"stackviz", world:"Rewriting Formulae", hook:"Operator precedence drives the stack." },
    { id:"9-36", section:"Prefix, Infix and Postfix Conversions", title:"Infix to Prefix Conversion", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-10", section:"Prefix, Infix and Postfix Conversions", title:"Prefix to Infix Conversion", difficulty:"M", viz:"stackviz", world:"Rewriting Formulae", hook:"Scan right to left, rebuild as you go." },
    { id:"9-34", section:"Prefix, Infix and Postfix Conversions", title:"Prefix to Postfix Conversion", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-11", section:"Prefix, Infix and Postfix Conversions", title:"Postfix to Infix Conversion", difficulty:"M", viz:"stackviz", world:"Rewriting Formulae", hook:"Pop two, wrap in brackets, push back." },
    { id:"9-35", section:"Prefix, Infix and Postfix Conversions", title:"Postfix to Prefix Conversion", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    // Monotonic Stack
    { id:"9-13", section:"Monotonic Stack", title:"Next Greater Element", difficulty:"M", viz:"stackviz", world:"Taller Neighbour", hook:"Who is the first taller person to your right?" },
    { id:"9-37", section:"Monotonic Stack", title:"Next Greater Element - 2", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-19", section:"Monotonic Stack", title:"Asteroid Collision", difficulty:"M", viz:"particles", world:"Asteroid Belt", hook:"The stack models survivors of each collision." },
    { id:"9-18", section:"Monotonic Stack", title:"Sum of Subarray Minimums", difficulty:"M", viz:"stackviz", world:"Counting Spans", hook:"Each element's span of dominance, counted once." },
    { id:"9-20", section:"Monotonic Stack", title:"Sum of Subarray Ranges", difficulty:"M", viz:"stackviz", world:"Counting Spans", hook:"Maximums minus minimums, both by the same trick." },
    { id:"9-21", section:"Monotonic Stack", title:"Remove K Digits", difficulty:"M", viz:"stackviz", world:"Trimming a Number", hook:"Greedily drop any digit bigger than its successor." },
    { id:"9-15", section:"Monotonic Stack", title:"Next Smaller Element", difficulty:"M", viz:"stackviz", world:"Shorter Neighbour", hook:"The same stack, flipped comparison." },
    // FAQs
    { id:"9-8", section:"FAQs", title:"Implement Min Stack", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"Store the running minimum alongside each value." },
    { id:"9-24", section:"FAQs", title:"Sliding Window Maximum", difficulty:"H", viz:"windowslide", world:"Moving Window", hook:"A deque holding only useful candidates." },
    { id:"9-17", section:"FAQs", title:"Trapping Rainwater", difficulty:"H", viz:"mountain", world:"Rainwater Basin", hook:"Water above a bar is bounded by the smaller wall." },
    { id:"9-39", section:"FAQs", title:"Largest rectangle in a histogram", difficulty:"H", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-40", section:"FAQs", title:"Maximum Rectangles", difficulty:"H", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
    { id:"9-25", section:"FAQs", title:"Stock span problem", difficulty:"M", viz:"stockchart", world:"Stock Streak", hook:"How many days back was it never higher?" },
    { id:"9-26", section:"FAQs", title:"Celebrity Problem", difficulty:"M", viz:"social", world:"The Celebrity", hook:"Every question eliminates one candidate." },
    { id:"9-27", section:"FAQs", title:"LRU Cache", difficulty:"H", viz:"linkedlist", world:"Cache Eviction", hook:"A hash map plus a doubly linked list." },
    { id:"9-28", section:"FAQs", title:"LFU Cache", difficulty:"H", viz:"linkedlist", world:"Cache Eviction", hook:"Frequency buckets, each an ordered list." },
    { id:"9-38", section:"FAQs", title:"Number of Greater Elements to the Right", difficulty:"M", viz:"stackviz", world:"Plate Stack", hook:"The stack remembers what is still open." },
  ]),
  S("Step 13", "Binary Trees", 32, [
    // Theory/Traversals
    { id:"13-66", section:"Theory/Traversals", title:"Introduction", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"13-38", section:"Theory/Traversals", title:"Inorder Traversal", difficulty:"E", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-3", section:"Theory/Traversals", title:"Preorder Traversal", difficulty:"E", viz:"treeviz", world:"Walking the Tree", hook:"Root first — how you'd copy a tree." },
    { id:"13-5", section:"Theory/Traversals", title:"Postorder Traversal", difficulty:"E", viz:"treeviz", world:"Walking the Tree", hook:"Children first — how you'd delete a tree." },
    { id:"13-6", section:"Theory/Traversals", title:"Level Order Traversal", difficulty:"M", viz:"bfs", world:"Floor by Floor", hook:"A queue turns depth into breadth." },
    { id:"13-37", section:"Theory/Traversals", title:"Pre, Post, Inorder in one traversal", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Medium Problems
    { id:"13-44", section:"Medium Problems", title:"Maximum Depth in BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-47", section:"Medium Problems", title:"Check if two trees are identical or not", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-45", section:"Medium Problems", title:"Check for balanced binary tree", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-46", section:"Medium Problems", title:"Diameter of Binary Tree", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-14", section:"Medium Problems", title:"Maximum path sum", difficulty:"H", viz:"treeviz", world:"Best Route", hook:"Return the best arm, record the best arch." },
    { id:"13-22", section:"Medium Problems", title:"Check for symmetrical BTs", difficulty:"M", viz:"mirror", world:"Mirror Test", hook:"Compare outer with outer, inner with inner." },
    { id:"13-55", section:"Medium Problems", title:"Children Sum Property in Binary Tree", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // FAQs
    { id:"13-48", section:"FAQs", title:"Zig Zag or Spiral Traversal", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-17", section:"FAQs", title:"Boundary Traversal", difficulty:"M", viz:"treeviz", world:"Tracing the Edge", hook:"Left edge, leaves, right edge reversed." },
    { id:"13-18", section:"FAQs", title:"Vertical Order Traversal", difficulty:"H", viz:"grid", world:"Column View", hook:"Sort by column, then row, then value." },
    { id:"13-49", section:"FAQs", title:"Top View of BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-50", section:"FAQs", title:"Bottom view of BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-51", section:"FAQs", title:"Right/Left View of BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-52", section:"FAQs", title:"Print root to leaf path in BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-53", section:"FAQs", title:"LCA in BT", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-54", section:"FAQs", title:"Maximum Width of BT", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-56", section:"FAQs", title:"Print all nodes at a distance of K in BT", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-57", section:"FAQs", title:"Minimum time taken to burn the BT from a given Node", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-58", section:"FAQs", title:"Count total nodes in a complete BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-35", section:"FAQs", title:"Flatten Binary Tree to Linked List", difficulty:"H", viz:"linkedlist", world:"Uncoiling", hook:"Right-skewed, in preorder." },
    // Construction Problems
    { id:"13-59", section:"Construction Problems", title:"Requirements needed to construct a unique BT", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree.", traceable:false },
    { id:"13-60", section:"Construction Problems", title:"Construct a BT from Preorder and Inorder", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-61", section:"Construction Problems", title:"Construct a BT from Postorder and Inorder", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-62", section:"Construction Problems", title:"Serialize and De-serialize BT", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Traversal in Constant Space
    { id:"13-64", section:"Traversal in Constant Space", title:"Morris Inorder Traversal", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"13-63", section:"Traversal in Constant Space", title:"Morris Preorder Traversal", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
  ]),
  S("Step 14", "Binary Search Trees", 15, [
    // Theory and Basics
    { id:"14-31", section:"Theory and Basics", title:"Introduction to BST", difficulty:"E", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space.", traceable:false, learning:true },
    { id:"14-18", section:"Theory and Basics", title:"Search in BST", difficulty:"E", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-19", section:"Theory and Basics", title:"Floor and Ceil in a BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-32", section:"Theory and Basics", title:"Find Min/Max in BST", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    // Medium
    { id:"14-21", section:"Medium", title:"Insert a given node in BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-7", section:"Medium", title:"Delete a node in BST", difficulty:"M", viz:"bst", world:"Filing Cabinet Reshuffle", hook:"Three cases — the two-child one needs a successor." },
    { id:"14-22", section:"Medium", title:"Kth Smallest and Largest element in BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-23", section:"Medium", title:"Check if a tree is a BST or not", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-24", section:"Medium", title:"LCA in BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-25", section:"Medium", title:"Construct a BST from a preorder traversal", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-26", section:"Medium", title:"Inorder successor and predecessor in BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    // FAQs
    { id:"14-33", section:"FAQs", title:"BST iterator", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-28", section:"FAQs", title:"Two sum in BST", difficulty:"M", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-29", section:"FAQs", title:"Correct BST with two nodes swapped", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
    { id:"14-30", section:"FAQs", title:"Largest BST in Binary Tree", difficulty:"H", viz:"binarysearch", world:"Halving the Search", hook:"Every probe discards half the space." },
  ]),
  S("Step 15", "Heaps", 20, [
    // Theory and Implementation
    { id:"11-18", section:"Theory and Implementation", title:"Heaps (Theory Video)", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"15-83", section:"Theory and Implementation", title:"Heapify Algorithm", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm." },
    { id:"15-84", section:"Theory and Implementation", title:"Build heap from a given Array", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm." },
    { id:"11-19", section:"Theory and Implementation", title:"Implement Min Heap", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"15-85", section:"Theory and Implementation", title:"Implement Max Heap", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm." },
    { id:"11-20", section:"Theory and Implementation", title:"Check if an array represents a min heap", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"11-4", section:"Theory and Implementation", title:"Convert Min Heap to Max Heap", difficulty:"M", viz:"heapviz", world:"Reversing Priority", hook:"Heapify from the last parent backwards." },
    { id:"15-86", section:"Theory and Implementation", title:"Heap Sort", difficulty:"H", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm." },
    { id:"11-21", section:"Theory and Implementation", title:"K-th Largest element in an array", difficulty:"H", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    // FAQs
    { id:"11-27", section:"FAQs", title:"Kth largest element in a stream of running integers", difficulty:"H", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"15-87", section:"FAQs", title:"Sort K sorted array", difficulty:"E", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison.", traceable:false, learning:true },
    { id:"11-23", section:"FAQs", title:"Merge K sorted Lists", difficulty:"H", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"11-24", section:"FAQs", title:"Replace Elements by Their Rank", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"11-10", section:"FAQs", title:"Task Scheduler", difficulty:"M", viz:"timeline", world:"Cooling Periods", hook:"The most frequent task sets the schedule length." },
    { id:"11-25", section:"FAQs", title:"Hand of Straights", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"11-12", section:"FAQs", title:"Design Twitter", difficulty:"M", viz:"social", world:"Feed Assembly", hook:"Merge the k most recent from each followee." },
    { id:"11-26", section:"FAQs", title:"Minimum Cost to Connect Sticks", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"11-15", section:"FAQs", title:"Maximum Sum Combination", difficulty:"M", viz:"heapviz", world:"Best Pairings", hook:"Explore the frontier, not the full grid." },
    { id:"11-16", section:"FAQs", title:"Find Median from Data Stream", difficulty:"H", viz:"balance", world:"Balanced Scales", hook:"Two heaps, kept the same size." },
    { id:"11-28", section:"FAQs", title:"Top K Frequent Elements", difficulty:"M", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
  ]),
  S("Step 16", "Graphs", 46, [
    // Theory and traversals
    { id:"15-80", section:"Theory and traversals", title:"Introduction to Graph", difficulty:"E", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything.", traceable:false, learning:true },
    { id:"15-51", section:"Theory and traversals", title:"Traversal Techniques", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree.", traceable:false },
    { id:"15-3", section:"Theory and traversals", title:"Connected Components", difficulty:"M", viz:"graphs", world:"Separate Islands", hook:"One traversal per unvisited starting node." },
    // Traversal Problems
    { id:"15-6", section:"Traversal Problems", title:"Number of provinces", difficulty:"M", viz:"graphs", world:"Separate Islands", hook:"Counting connected components by another name." },
    { id:"15-7", section:"Traversal Problems", title:"Number of islands", difficulty:"M", viz:"grid", world:"Island Counting", hook:"A grid is a graph with implicit edges." },
    { id:"15-54", section:"Traversal Problems", title:"Flood fill algorithm", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-14", section:"Traversal Problems", title:"Number of enclaves", difficulty:"M", viz:"grid", world:"Landlocked", hook:"Anything reachable from the edge escapes." },
    { id:"15-9", section:"Traversal Problems", title:"Rotten Oranges", difficulty:"M", viz:"grid", world:"Spreading Rot", hook:"Multi-source BFS measures time, not distance." },
    { id:"15-57", section:"Traversal Problems", title:"Distance of nearest cell having one", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-13", section:"Traversal Problems", title:"Surrounded Regions", difficulty:"M", viz:"grid", world:"Capturing Territory", hook:"Work from the border inwards." },
    { id:"16-81", section:"Traversal Problems", title:"Number of distinct islands", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Cycles
    { id:"15-56", section:"Cycles", title:"Detect a cycle in an undirected graph", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-58", section:"Cycles", title:"Bipartite graph", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-61", section:"Cycles", title:"Topological sort or Kahn's algorithm", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    { id:"15-62", section:"Cycles", title:"Detect a cycle in a directed graph", difficulty:"M", viz:"sorting", world:"Putting Things In Order", hook:"Order emerges from repeated comparison." },
    // Hard Problems
    { id:"15-23", section:"Hard Problems", title:"Find eventual safe states", difficulty:"H", viz:"graphs", world:"Safe Ground", hook:"Reverse the edges and run Kahn's." },
    { id:"15-21", section:"Hard Problems", title:"Course Schedule I", difficulty:"H", viz:"graphs", world:"Prerequisites", hook:"A valid order exists only without cycles." },
    { id:"15-22", section:"Hard Problems", title:"Course Schedule II", difficulty:"H", viz:"graphs", world:"Prerequisites", hook:"Return the order, not just whether one exists." },
    { id:"15-24", section:"Hard Problems", title:"Alien Dictionary", difficulty:"H", viz:"graphs", world:"Unknown Alphabet", hook:"Derive the edges from adjacent word pairs." },
    { id:"15-26", section:"Hard Problems", title:"Shortest path in DAG", difficulty:"M", viz:"graphs", world:"One-Way Streets", hook:"Topological order removes the need for a heap." },
    { id:"15-63", section:"Hard Problems", title:"Shortest path in undirected graph with unit weights", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-15", section:"Hard Problems", title:"Word ladder I", difficulty:"H", viz:"bfs", world:"Word Chain", hook:"Words are nodes; one-letter edits are edges." },
    { id:"15-16", section:"Hard Problems", title:"Word ladder II", difficulty:"H", viz:"bfs", world:"Word Chain", hook:"BFS for distance, then backtrack every shortest path." },
    // Shortest Path Algorithms
    { id:"15-64", section:"Shortest Path Algorithms", title:"Dijkstra's algorithm", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"16-82", section:"Shortest Path Algorithms", title:"Print Shortest Path", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-66", section:"Shortest Path Algorithms", title:"Shortest Distance in a Binary Maze", difficulty:"M", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-29", section:"Shortest Path Algorithms", title:"Path with minimum effort", difficulty:"M", viz:"mountain", world:"Gentlest Climb", hook:"Minimise the largest single step." },
    { id:"15-67", section:"Shortest Path Algorithms", title:"Cheapest flight within K stops", difficulty:"H", viz:"heapviz", world:"Triage Queue", hook:"The most urgent rises to the top." },
    { id:"15-68", section:"Shortest Path Algorithms", title:"Minimum multiplications to reach end", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-32", section:"Shortest Path Algorithms", title:"Number of ways to arrive at destination", difficulty:"H", viz:"dijkstra", world:"Counting Routes", hook:"Carry a path count alongside the distance." },
    { id:"15-69", section:"Shortest Path Algorithms", title:"Bellman ford algorithm", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-70", section:"Shortest Path Algorithms", title:"Floyd warshall algorithm", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-71", section:"Shortest Path Algorithms", title:"Find the city with the smallest number of neighbors", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-31", section:"Shortest Path Algorithms", title:"Network Delay Time", difficulty:"M", viz:"dijkstra", world:"Signal Spread", hook:"The slowest destination sets the answer." },
    { id:"15-76", section:"Shortest Path Algorithms", title:"Swim in Rising Water", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Minimum Spanning Tree
    { id:"15-72", section:"Minimum Spanning Tree", title:"MST theory", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"15-73", section:"Minimum Spanning Tree", title:"Disjoint Set", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    { id:"15-74", section:"Minimum Spanning Tree", title:"Find the MST weight", difficulty:"M", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Hard Problems II
    { id:"15-40", section:"Hard Problems II", title:"Number of operations to make network connected", difficulty:"M", viz:"social", world:"Rewiring", hook:"Spare cables must cover the component gaps." },
    { id:"15-41", section:"Hard Problems II", title:"Accounts merge", difficulty:"M", viz:"social", world:"Merging Identities", hook:"Emails are the edges between accounts." },
    { id:"15-42", section:"Hard Problems II", title:"Number of islands II", difficulty:"H", viz:"grid", world:"Rising Land", hook:"Union-find handles land appearing over time." },
    { id:"15-43", section:"Hard Problems II", title:"Making a large island", difficulty:"H", viz:"grid", world:"Land Reclamation", hook:"Size each island once, then test each water cell." },
    { id:"15-75", section:"Hard Problems II", title:"Most stones removed with same row or column", difficulty:"H", viz:"treeviz", world:"Family Tree", hook:"One root, and every node a smaller tree." },
    // Additional Algorithms
    { id:"15-79", section:"Additional Algorithms", title:"Kosaraju's algorithm", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-77", section:"Additional Algorithms", title:"Bridges in graph", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-78", section:"Additional Algorithms", title:"Articulation point in graph", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
  ]),
  S("Step 17", "Dynamic Programming", 53, [
    // Introduction
    { id:"16-79", section:"Introduction", title:"Introduction to DP", difficulty:"E", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time.", traceable:false, learning:true },
    // 1D DP
    { id:"16-2", section:"1D DP", title:"Climbing stairs", difficulty:"M", viz:"dp", world:"Climbing Steps", hook:"Fibonacci wearing a staircase." },
    { id:"16-3", section:"1D DP", title:"Frog Jump", difficulty:"M", viz:"dp", world:"Stepping Stones", hook:"Cost, not count — the first real DP." },
    { id:"16-4", section:"1D DP", title:"Frog jump with K distances", difficulty:"M", viz:"dp", world:"Stepping Stones", hook:"K choices per state instead of two." },
    { id:"16-55", section:"1D DP", title:"Maximum sum of non adjacent elements", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-56", section:"1D DP", title:"House robber", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    // 2D DP
    { id:"16-7", section:"2D DP", title:"Ninja's training", difficulty:"M", viz:"dpgrid", world:"Daily Schedule", hook:"State is the day plus yesterday's choice." },
    // DP on grids
    { id:"16-57", section:"DP on grids", title:"Grid unique paths", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-58", section:"DP on grids", title:"Unique paths II", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-59", section:"DP on grids", title:"Minimum Falling Path Sum", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-60", section:"DP on grids", title:"Triangle", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-61", section:"DP on grids", title:"Cherry pickup II", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"17-12", section:"DP on grids", title:"Count Square Submatrices with All Ones|(DP-56)", difficulty:"E", viz:"dpgrid", world:"The Memo Vault", hook:"Remember the past to conquer the future.", traceable:false, learning:true },
    // DP on stocks
    { id:"16-35", section:"DP on stocks", title:"Best time to buy and sell stock", difficulty:"M", viz:"stockchart", world:"Stock Market", hook:"Remember the cheapest day behind you." },
    { id:"16-70", section:"DP on stocks", title:"Best time to buy and sell stock II", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-71", section:"DP on stocks", title:"Best time to buy and sell stock III", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-72", section:"DP on stocks", title:"Best time to buy and sell stock IV", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-74", section:"DP on stocks", title:"Best time to buy and sell stock with transaction fees", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-73", section:"DP on stocks", title:"Best Time to Buy and Sell Stock with Cooldown", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    // DP on subsequences
    { id:"16-62", section:"DP on subsequences", title:"Subset sum equals to target", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-15", section:"DP on subsequences", title:"Partition equal subset sum", difficulty:"M", viz:"balance", world:"Balanced Scales", hook:"Target is half the total — or it's impossible." },
    { id:"16-63", section:"DP on subsequences", title:"Partition a set into two subsets with minimum absolute sum difference", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-17", section:"DP on subsequences", title:"Count subsets with sum K", difficulty:"M", viz:"dpgrid", world:"Counting Ways", hook:"Zeros make the base case subtle." },
    { id:"16-18", section:"DP on subsequences", title:"Count partitions with given difference", difficulty:"M", viz:"dpgrid", world:"Counting Ways", hook:"Rearranges into a count-subsets problem." },
    { id:"17-13", section:"DP on subsequences", title:"0 and 1 Knapsack", difficulty:"M", viz:"dpgrid", world:"The Memo Vault", hook:"Remember the past to conquer the future." },
    { id:"16-64", section:"DP on subsequences", title:"Minimum coins", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-21", section:"DP on subsequences", title:"Target sum", difficulty:"M", viz:"dpgrid", world:"Signs and Sums", hook:"Assigning signs is partitioning in disguise." },
    { id:"16-65", section:"DP on subsequences", title:"Coin change II", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-23", section:"DP on subsequences", title:"Unbounded knapsack", difficulty:"M", viz:"vault", world:"Unlimited Stock", hook:"The index doesn't advance when you take." },
    { id:"16-66", section:"DP on subsequences", title:"Rod cutting problem", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    // LIS
    { id:"16-41", section:"LIS", title:"Longest Increasing Subsequence", difficulty:"M", viz:"mountain", world:"Rising Path", hook:"The O(n log n) version isn't the actual subsequence." },
    { id:"16-42", section:"LIS", title:"Print Longest Increasing Subsequence", difficulty:"H", viz:"mountain", world:"Rising Path", hook:"Track predecessors to recover it." },
    { id:"16-43", section:"LIS", title:"Largest Divisible Subset", difficulty:"M", viz:"mountain", world:"Divisible Chain", hook:"Sort first, then it's LIS with a divisibility test." },
    { id:"16-44", section:"LIS", title:"Longest String Chain", difficulty:"M", viz:"trie", world:"Word Chain", hook:"LIS where the order is 'is a predecessor of'." },
    { id:"16-45", section:"LIS", title:"Longest Bitonic Subsequence", difficulty:"M", viz:"mountain", world:"Up Then Down", hook:"LIS forwards plus LIS backwards." },
    { id:"16-46", section:"LIS", title:"Number of Longest Increasing Subsequences", difficulty:"M", viz:"mountain", world:"Counting Paths", hook:"Carry a count alongside each length." },
    // DP on strings
    { id:"16-25", section:"DP on strings", title:"Longest common subsequence", difficulty:"M", viz:"dna", world:"DNA Alignment", hook:"Find the sequence two strands share." },
    { id:"16-27", section:"DP on strings", title:"Longest common substring", difficulty:"M", viz:"dna", world:"DNA Alignment", hook:"A mismatch resets to zero, unlike LCS." },
    { id:"16-28", section:"DP on strings", title:"Longest palindromic subsequence", difficulty:"M", viz:"mirror", world:"Mirror Sequence", hook:"LCS of the string with its reverse." },
    { id:"16-68", section:"DP on strings", title:"Minimum insertions to make string palindrome", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-69", section:"DP on strings", title:"Minimum insertions or deletions to convert string A to B", difficulty:"M", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
    { id:"16-31", section:"DP on strings", title:"Shortest common supersequence", difficulty:"H", viz:"dna", world:"Merged Strand", hook:"Both strings, sharing the LCS once." },
    { id:"16-32", section:"DP on strings", title:"Distinct subsequences", difficulty:"H", viz:"dna", world:"Counting Matches", hook:"Match or skip — counts, not lengths." },
    { id:"16-33", section:"DP on strings", title:"Edit distance", difficulty:"H", viz:"dna", world:"Spell Check", hook:"How many keystrokes turn one word into another?" },
    { id:"16-34", section:"DP on strings", title:"Wildcard matching", difficulty:"H", viz:"dna", world:"Pattern Matching", hook:"A star can consume nothing, or everything." },
    { id:"7-21", section:"DP on strings", title:"Word Break", difficulty:"M", viz:"backtrack", world:"Splitting Text", hook:"Memoise or the branching kills you." },
    { id:"18-13", section:"DP on strings", title:"Count Palindromic Subsequences", difficulty:"H", viz:"dpgrid", world:"The Memo Vault", hook:"Remember the past to conquer the future." },
    // MCM DP
    { id:"16-47", section:"MCM DP", title:"Matrix chain multiplication", difficulty:"H", viz:"dpgrid", world:"Order of Operations", hook:"Try every split point as the last multiply." },
    { id:"16-49", section:"MCM DP", title:"Burst balloons", difficulty:"H", viz:"particles", world:"Bursting Order", hook:"Think about which balloon bursts last." },
    { id:"16-51", section:"MCM DP", title:"Palindrome partitioning II", difficulty:"H", viz:"mirror", world:"Cutting a String", hook:"Front partition, with a palindrome precheck." },
    { id:"16-52", section:"MCM DP", title:"Partition Array for Maximum Sum", difficulty:"H", viz:"dpgrid", world:"Chunking", hook:"Try every chunk length ending here." },
    { id:"16-48", section:"MCM DP", title:"Minimum cost to cut the stick", difficulty:"H", viz:"dpgrid", world:"Cutting Stock", hook:"Add the ends and the interval DP appears." },
    { id:"16-77", section:"MCM DP", title:"Different Ways to Evaluate a Boolean Expression", difficulty:"H", viz:"grid", world:"Printing Patterns", hook:"Nested loops, one row at a time." },
  ]),
  S("Step 18", "Tries", 7, [
    // Theory
    { id:"18-14", section:"Theory", title:"Bit PreRequisites for TRIE Problems", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"17-8", section:"Theory", title:"Trie Implementation and Operations", difficulty:"M", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm." },
    { id:"17-9", section:"Theory", title:"Trie Implementation and Advanced Operations", difficulty:"M", viz:"trie", world:"Prefix Tree", hook:"Words that start the same share a path." },
    // Problems
    { id:"17-3", section:"Problems", title:"Longest Word with All Prefixes", difficulty:"M", viz:"trie", world:"Buildable Words", hook:"Every prefix must itself be a word." },
    { id:"17-10", section:"Problems", title:"Number of distinct substrings in a string", difficulty:"H", viz:"bst", world:"Filing Cabinet", hook:"Left is smaller, right is bigger — always." },
    { id:"17-5", section:"Problems", title:"Maximum XOR of two numbers in an array", difficulty:"M", viz:"circuit", world:"Bitwise Trie", hook:"Store bits, then greedily take the opposite branch." },
    { id:"17-11", section:"Problems", title:"Maximum Xor with an element from an array", difficulty:"H", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
  ]),
  S("Step 19", "Strings (Advanced Algo)", 9, [
    // Medium Problems
    { id:"5-21", section:"Medium Problems", title:"Reverse every word in a string", difficulty:"M", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"18-10", section:"Medium Problems", title:"Minimum number of bracket reversals to make an expression balanced", difficulty:"M", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"18-2", section:"Medium Problems", title:"Count and say", difficulty:"M", viz:"terminal", world:"Run-Length Speech", hook:"Each term describes the one before it." },
    // Advanced Problems (Less asked)
    { id:"19-1", section:"Advanced Problems (Less asked)", title:"Hashing In Strings | Theory", difficulty:"E", viz:"terminal", world:"Language Basics", hook:"Groundwork, not an algorithm.", traceable:false, learning:true },
    { id:"18-11", section:"Advanced Problems (Less asked)", title:"Rabin Karp Algorithm", difficulty:"H", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"19-2", section:"Advanced Problems (Less asked)", title:"Z function", difficulty:"H", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"18-12", section:"Advanced Problems (Less asked)", title:"KMP Algorithm or LPS array", difficulty:"H", viz:"dna", world:"Genetic Sequence", hook:"Characters chained together." },
    { id:"19-3", section:"Advanced Problems (Less asked)", title:"Shortest Palindrome", difficulty:"H", viz:"graphs", world:"Road Network", hook:"Nodes and edges — the shape of almost everything." },
    { id:"18-7", section:"Advanced Problems (Less asked)", title:"Longest happy prefix", difficulty:"H", viz:"dna", world:"Prefix Equals Suffix", hook:"Exactly what the LPS array computes." },
  ]),
  S("Step 20", "Maths", 3, [
    // Sieve of Eratosthenes
    { id:"20-1", section:"Sieve of Eratosthenes", title:"Print all primes till N", difficulty:"M", viz:"searchbeam", world:"Number Theory", hook:"Arithmetic you can watch." },
    { id:"8-33", section:"Sieve of Eratosthenes", title:"Prime factorisation of a Number", difficulty:"M", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
    { id:"8-32", section:"Sieve of Eratosthenes", title:"Count primes in range L to R", difficulty:"H", viz:"circuit", world:"Row of Switches", hook:"Every integer is a row of on/off switches." },
  ]),
];

export default A2Z_STEPS;
