// ── STRIVER'S A2Z SHEET ────────────────────────────────────────────────────
//
// The full 18-step sheet. data.js previously carried a 7-step, 72-problem
// stub; this is the complete structure.
//
// Shape per problem:
//   id         "<step>-<n>" — progress.js keys off this, so ids are
//              APPEND-ONLY. Never renumber an existing problem or you silently
//              reassign someone's completed work to a different problem.
//   title      the problem as the sheet names it
//   difficulty E | M | H
//   viz        a scene builder from vizScenes.js (an unknown name falls back
//              to `default`, so a wrong guess degrades rather than breaks)
//   world      the real-world framing shown in the problem viewer
//   hook       one line on what the problem actually teaches
//   section    the sheet's sub-section, used to group the longer steps
//
// `progress` on a step is legacy display data; real progress comes from
// progress.js. It is 0 here so nothing claims completion the student
// hasn't earned.

const S = (step, title, problems) => ({ step, title, progress: 0, problems });

export const A2Z_STEPS = [
  S("Step 1", "Learn the Basics", [
    { id:"1-1",  section:"Basics",    title:"User Input / Output",            difficulty:"E", viz:"terminal",  world:"ATM Machine",          hook:"Every program starts with a conversation." },
    { id:"1-2",  section:"Basics",    title:"Data Types",                     difficulty:"E", viz:"warehouse", world:"Warehouse Shelves",    hook:"Every shelf holds a different kind of cargo." },
    { id:"1-3",  section:"Basics",    title:"If-Else / Switch Statements",    difficulty:"E", viz:"traffic",   world:"Traffic Signal",       hook:"Rules decide who moves and who waits." },
    { id:"1-4",  section:"Basics",    title:"Arrays",                         difficulty:"E", viz:"array",     world:"Train Carriages",      hook:"A line of boxes, each with an address." },
    { id:"1-5",  section:"Basics",    title:"Strings",                        difficulty:"E", viz:"dna",       world:"DNA Strand",           hook:"Characters chained together like genetic code." },
    { id:"1-6",  section:"Basics",    title:"For Loops",                      difficulty:"E", viz:"conveyor",  world:"Factory Conveyor",     hook:"The machine that never gets tired." },
    { id:"1-7",  section:"Basics",    title:"While Loops",                    difficulty:"E", viz:"watchman",  world:"Security Guard",       hook:"Keep checking until the condition is met." },
    { id:"1-8",  section:"Basics",    title:"Functions (Pass by Value/Ref)",  difficulty:"E", viz:"courier",   world:"Courier Service",      hook:"Send a copy, or send the real thing?" },
    { id:"1-9",  section:"Basics",    title:"Time Complexity",                difficulty:"M", viz:"racetrack", world:"Formula 1 Race",       hook:"How fast does your code cross the finish line?" },
    { id:"1-10", section:"Basics",    title:"Space Complexity",               difficulty:"M", viz:"warehouse", world:"RAM as Warehouse",     hook:"How much floor space does your solution rent?" },

    { id:"1-11", section:"Maths",     title:"Count Digits",                   difficulty:"E", viz:"terminal",  world:"Odometer",             hook:"Peeling a number apart one digit at a time." },
    { id:"1-12", section:"Maths",     title:"Reverse a Number",               difficulty:"E", viz:"mirror",    world:"Mirror Writing",       hook:"Build the answer backwards as you strip the input." },
    { id:"1-13", section:"Maths",     title:"Check Palindrome",               difficulty:"E", viz:"mirror",    world:"Mirror Test",          hook:"Does it read the same from both ends?" },
    { id:"1-14", section:"Maths",     title:"GCD or HCF",                     difficulty:"E", viz:"balance",   world:"Tiling a Floor",       hook:"The largest tile that fits both sides exactly." },
    { id:"1-15", section:"Maths",     title:"Armstrong Numbers",              difficulty:"E", viz:"particles", world:"Self-Describing Code", hook:"A number built from its own digits." },
    { id:"1-16", section:"Maths",     title:"Print all Divisors",             difficulty:"E", viz:"grid",      world:"Rectangle Factory",    hook:"Only check to √n — divisors come in pairs." },
    { id:"1-17", section:"Maths",     title:"Check for Prime",                difficulty:"E", viz:"searchbeam", world:"Prime Detector",      hook:"One failed division is enough to disqualify." },

    { id:"1-18", section:"Recursion", title:"Understand Recursion (Print Name N Times)", difficulty:"E", viz:"fractal", world:"Hall of Mirrors", hook:"A function that calls itself needs a way to stop." },
    { id:"1-19", section:"Recursion", title:"Print 1 to N",                   difficulty:"E", viz:"fractal",   world:"Countdown",            hook:"Where you print decides the order." },
    { id:"1-20", section:"Recursion", title:"Print N to 1",                   difficulty:"E", viz:"fractal",   world:"Reverse Countdown",    hook:"The same recursion, printed on the way back up." },
    { id:"1-21", section:"Recursion", title:"Sum of First N Numbers",         difficulty:"E", viz:"fractal",   world:"Stacking Coins",       hook:"Parameterised versus functional recursion." },
    { id:"1-22", section:"Recursion", title:"Factorial of N",                 difficulty:"E", viz:"fractal",   world:"Nested Boxes",         hook:"Each call waits for the smaller one beneath it." },
    { id:"1-23", section:"Recursion", title:"Reverse an Array",               difficulty:"E", viz:"mirror",    world:"Reversing a Queue",    hook:"Two pointers walking inward, recursively." },
    { id:"1-24", section:"Recursion", title:"Check String Palindrome",        difficulty:"E", viz:"mirror",    world:"Mirror Test",          hook:"Compare the ends, then recurse on the middle." },
    { id:"1-25", section:"Recursion", title:"Fibonacci Number",               difficulty:"E", viz:"fractal",   world:"Rabbit Pairs",         hook:"The call tree explodes — this is why memoisation exists." },

    { id:"1-26", section:"Hashing",   title:"Count Frequencies of Elements",  difficulty:"E", viz:"votes",     world:"Vote Tally",           hook:"One pass to count, instant lookup after." },
    { id:"1-27", section:"Hashing",   title:"Highest/Lowest Frequency Element", difficulty:"E", viz:"leaderboard", world:"Poll Results",     hook:"Count first, then read the winner off the tally." },
  ]),

  S("Step 2", "Sorting Techniques", [
    { id:"2-1", section:"Sorting I",  title:"Selection Sort",           difficulty:"E", viz:"leaderboard", world:"Leaderboard Selection", hook:"Find the champion, move them to the top. Repeat." },
    { id:"2-2", section:"Sorting I",  title:"Bubble Sort",              difficulty:"E", viz:"bubbles",     world:"Bubble Tea Queue",      hook:"Heavy bubbles sink; light ones rise." },
    { id:"2-3", section:"Sorting I",  title:"Insertion Sort",           difficulty:"E", viz:"cards",       world:"Sorting Playing Cards", hook:"Pick a card, slide it into the right slot." },
    { id:"2-4", section:"Sorting II", title:"Merge Sort",               difficulty:"M", viz:"mergesort",   world:"Merging Sorted Piles",  hook:"Divide the chaos. Merge into order." },
    { id:"2-5", section:"Sorting II", title:"Recursive Bubble Sort",    difficulty:"E", viz:"bubbles",     world:"Bubble Tea Queue",      hook:"The same passes, expressed as recursion." },
    { id:"2-6", section:"Sorting II", title:"Recursive Insertion Sort", difficulty:"E", viz:"cards",       world:"Sorting Playing Cards", hook:"Sort the first n-1, then place the last." },
    { id:"2-7", section:"Sorting II", title:"Quick Sort",               difficulty:"M", viz:"quicksort",   world:"Pivot Party",           hook:"Pick a pivot — the crowd splits around it." },
  ]),

  S("Step 3", "Arrays", [
    { id:"3-1",  section:"Easy",   title:"Largest Element in Array",            difficulty:"E", viz:"leaderboard", world:"Tallest in the Room", hook:"One pass, one running champion." },
    { id:"3-2",  section:"Easy",   title:"Second Largest Without Sorting",      difficulty:"E", viz:"podium",      world:"Silver Medal",        hook:"Two runners-up tracked in a single sweep." },
    { id:"3-3",  section:"Easy",   title:"Check if Array is Sorted",            difficulty:"E", viz:"array",       world:"Queue Inspection",    hook:"One out-of-order pair is enough to fail." },
    { id:"3-4",  section:"Easy",   title:"Remove Duplicates from Sorted Array", difficulty:"E", viz:"dedup",       world:"Guest List Cleanup",  hook:"A write pointer trailing a read pointer." },
    { id:"3-5",  section:"Easy",   title:"Left Rotate Array by One",            difficulty:"E", viz:"carousel",    world:"Carousel",            hook:"Everyone shifts one seat; the first wraps around." },
    { id:"3-6",  section:"Easy",   title:"Left Rotate Array by K Places",       difficulty:"M", viz:"carousel",    world:"Carousel",            hook:"Three reversals beat K separate shifts." },
    { id:"3-7",  section:"Easy",   title:"Move Zeros to End",                   difficulty:"E", viz:"conveyor",    world:"Sorting Belt",        hook:"Keep order for the rest while zeros sink." },
    { id:"3-8",  section:"Easy",   title:"Linear Search",                       difficulty:"E", viz:"searchbeam",  world:"Door-to-Door",        hook:"The baseline every faster search is measured against." },
    { id:"3-9",  section:"Easy",   title:"Union of Two Sorted Arrays",          difficulty:"M", viz:"venn",        world:"Merging Guest Lists", hook:"Two pointers, no duplicates." },
    { id:"3-10", section:"Easy",   title:"Intersection of Two Sorted Arrays",   difficulty:"E", viz:"venn",        world:"Mutual Friends",      hook:"Advance whichever side is behind." },
    { id:"3-11", section:"Easy",   title:"Find Missing Number",                 difficulty:"E", viz:"seats",       world:"Empty Seat",          hook:"XOR or sum — both beat sorting." },
    { id:"3-12", section:"Easy",   title:"Maximum Consecutive Ones",            difficulty:"E", viz:"array",       world:"Winning Streak",      hook:"Reset the counter the moment the streak breaks." },
    { id:"3-13", section:"Easy",   title:"Number Appearing Once (others twice)", difficulty:"E", viz:"particles",  world:"The Odd One Out",     hook:"XOR cancels every pair and leaves the loner." },
    { id:"3-14", section:"Easy",   title:"Longest Subarray with Sum K (positives)", difficulty:"M", viz:"windowslide", world:"Sliding Window",  hook:"Grow right, shrink left — never restart." },
    { id:"3-15", section:"Easy",   title:"Longest Subarray with Sum K (any sign)", difficulty:"M", viz:"stockchart", world:"Ledger Balance",    hook:"Prefix sums in a map — the window trick breaks here." },

    { id:"3-16", section:"Medium", title:"Two Sum",                             difficulty:"M", viz:"twopointers", world:"Shopping Budget",     hook:"Hash what you've seen, not what's coming." },
    { id:"3-17", section:"Medium", title:"Sort an Array of 0s, 1s and 2s",      difficulty:"M", viz:"sorting",        world:"Dutch National Flag", hook:"Three pointers sort three values in one pass." },
    { id:"3-18", section:"Medium", title:"Majority Element (> n/2)",            difficulty:"M", viz:"votes",    world:"Landslide Vote",      hook:"Boyer-Moore: cancel opposing votes until one survives." },
    { id:"3-19", section:"Medium", title:"Kadane's Algorithm",                  difficulty:"M", viz:"stockchart",  world:"Best Trading Streak", hook:"Extend the run, or cut your losses." },
    { id:"3-20", section:"Medium", title:"Print Subarray with Maximum Sum",     difficulty:"M", viz:"stockchart",  world:"Best Trading Streak", hook:"Track where the winning run started." },
    { id:"3-21", section:"Medium", title:"Best Time to Buy and Sell Stock",     difficulty:"E", viz:"stockchart",  world:"Stock Market",        hook:"Remember the cheapest day behind you." },
    { id:"3-22", section:"Medium", title:"Rearrange Array by Sign",             difficulty:"M", viz:"twopointers",       world:"Alternating Teams",   hook:"Two write cursors, one for each sign." },
    { id:"3-23", section:"Medium", title:"Next Permutation",                    difficulty:"M", viz:"sorting",     world:"Dictionary Order",    hook:"Find the pivot, swap the smallest bigger, reverse the tail." },
    { id:"3-24", section:"Medium", title:"Leaders in an Array",                 difficulty:"E", viz:"mountain",    world:"Mountain Peaks",      hook:"Scan from the right and keep the running maximum." },
    { id:"3-25", section:"Medium", title:"Longest Consecutive Sequence",        difficulty:"M", viz:"train",       world:"Rebuilding a Chain",  hook:"Only start counting from a true sequence head." },
    { id:"3-26", section:"Medium", title:"Set Matrix Zeros",                    difficulty:"M", viz:"grid",        world:"Spreadsheet Wipe",    hook:"Use row 0 and column 0 as your own bookkeeping." },
    { id:"3-27", section:"Medium", title:"Rotate Matrix by 90 Degrees",         difficulty:"M", viz:"grid",        world:"Turning a Photo",     hook:"Transpose, then reverse each row." },
    { id:"3-28", section:"Medium", title:"Spiral Traversal of Matrix",          difficulty:"M", viz:"grid",        world:"Peeling an Onion",    hook:"Four shrinking boundaries, walked in turn." },
    { id:"3-29", section:"Medium", title:"Count Subarrays with Given Sum",      difficulty:"M", viz:"stockchart",  world:"Ledger Audit",        hook:"Every prefix you've seen is a potential left edge." },

    { id:"3-30", section:"Hard",   title:"Pascal's Triangle",                   difficulty:"M", viz:"fractal",     world:"Stacked Bricks",      hook:"Each brick is the sum of the two beneath it." },
    { id:"3-31", section:"Hard",   title:"Majority Elements (> n/3)",           difficulty:"H", viz:"votes",    world:"Three-Way Race",      hook:"At most two candidates can clear a third of the vote." },
    { id:"3-32", section:"Hard",   title:"3 Sum",                               difficulty:"H", viz:"twopointers", world:"Three-Way Split",     hook:"Fix one, two-pointer the rest — sorting makes it work." },
    { id:"3-33", section:"Hard",   title:"4 Sum",                               difficulty:"H", viz:"twopointers", world:"Four-Way Split",      hook:"The same idea nested one level deeper." },
    { id:"3-34", section:"Hard",   title:"Largest Subarray with 0 Sum",         difficulty:"M", viz:"stockchart",  world:"Break-Even Streak",   hook:"A repeated prefix sum means the gap sums to zero." },
    { id:"3-35", section:"Hard",   title:"Count Subarrays with Given XOR",      difficulty:"H", viz:"circuit",     world:"Parity Check",        hook:"Prefix XOR behaves exactly like prefix sum." },
    { id:"3-36", section:"Hard",   title:"Merge Overlapping Subintervals",      difficulty:"M", viz:"timeline",    world:"Calendar Merge",      hook:"Sort by start and the overlaps fall out in one pass." },
    { id:"3-37", section:"Hard",   title:"Merge Two Sorted Arrays Without Extra Space", difficulty:"M", viz:"mergesort", world:"Two Shelves, One Order", hook:"The gap method, or a careful backward walk." },
    { id:"3-38", section:"Hard",   title:"Find Repeating and Missing Number",   difficulty:"H", viz:"seats",       world:"Duplicate Ticket",    hook:"Two equations, two unknowns." },
    { id:"3-39", section:"Hard",   title:"Count Inversions",                    difficulty:"H", viz:"mergesort",   world:"Measuring Disorder",  hook:"Merge sort counts them for free while it merges." },
    { id:"3-40", section:"Hard",   title:"Reverse Pairs",                       difficulty:"H", viz:"mergesort",   world:"Steep Drops",         hook:"A second scan inside the merge, same O(n log n)." },
    { id:"3-41", section:"Hard",   title:"Maximum Product Subarray",            difficulty:"M", viz:"stockchart",  world:"Compounding Returns", hook:"A negative can become the best — track min and max." },
  ]),

  S("Step 4", "Binary Search", [
    { id:"4-1",  section:"BS on 1D",     title:"Binary Search to Find X",          difficulty:"E", viz:"binarysearch", world:"Library Catalog",    hook:"Halve the search space with every guess." },
    { id:"4-2",  section:"BS on 1D",     title:"Lower Bound",                      difficulty:"E", viz:"binarysearch", world:"First Fit",          hook:"The first index not less than the target." },
    { id:"4-3",  section:"BS on 1D",     title:"Upper Bound",                      difficulty:"E", viz:"binarysearch", world:"Just Past It",       hook:"The first index strictly greater." },
    { id:"4-4",  section:"BS on 1D",     title:"Search Insert Position",           difficulty:"E", viz:"binarysearch", world:"Shelving a Book",    hook:"Where it would go if it isn't already there." },
    { id:"4-5",  section:"BS on 1D",     title:"Floor and Ceil in Sorted Array",   difficulty:"E", viz:"binarysearch", world:"Nearest Neighbours", hook:"The closest value on each side." },
    { id:"4-6",  section:"BS on 1D",     title:"First and Last Occurrence",        difficulty:"E", viz:"binarysearch", world:"Edges of a Block",   hook:"Two biased searches instead of one." },
    { id:"4-7",  section:"BS on 1D",     title:"Count Occurrences in Sorted Array", difficulty:"E", viz:"binarysearch", world:"Counting Copies",   hook:"Last minus first, plus one." },
    { id:"4-8",  section:"BS on 1D",     title:"Search in Rotated Sorted Array",   difficulty:"M", viz:"binarysearch", world:"Rotated Dial",       hook:"One half is always sorted — decide which." },
    { id:"4-9",  section:"BS on 1D",     title:"Search in Rotated Array II (duplicates)", difficulty:"M", viz:"binarysearch", world:"Rotated Dial", hook:"Duplicates blind the halves; shrink and retry." },
    { id:"4-10", section:"BS on 1D",     title:"Minimum in Rotated Sorted Array",  difficulty:"M", viz:"binarysearch", world:"Finding the Seam",   hook:"The pivot is the only place order breaks." },
    { id:"4-11", section:"BS on 1D",     title:"Find How Many Times Array Rotated", difficulty:"E", viz:"binarysearch", world:"Reading the Dial",  hook:"The index of the minimum is the rotation count." },
    { id:"4-12", section:"BS on 1D",     title:"Single Element in Sorted Array",   difficulty:"M", viz:"binarysearch", world:"The Odd One Out",    hook:"Pair indices shift after the loner." },
    { id:"4-13", section:"BS on 1D",     title:"Find Peak Element",                difficulty:"M", viz:"mountain",     world:"Hill Climbing",      hook:"Walk uphill — a peak must exist that way." },

    { id:"4-14", section:"BS on Answer", title:"Square Root of a Number",          difficulty:"E", viz:"binarysearch", world:"Guess and Narrow",   hook:"Search the answer, not the array." },
    { id:"4-15", section:"BS on Answer", title:"Nth Root of a Number",             difficulty:"M", viz:"binarysearch", world:"Guess and Narrow",   hook:"The same search with a different test." },
    { id:"4-16", section:"BS on Answer", title:"Koko Eating Bananas",              difficulty:"M", viz:"binarysearch", world:"Eating Rate",        hook:"Feasibility is monotonic — that is what makes it searchable." },
    { id:"4-17", section:"BS on Answer", title:"Minimum Days to Make M Bouquets",  difficulty:"M", viz:"binarysearch", world:"Blooming Garden",    hook:"Search the day; check feasibility linearly." },
    { id:"4-18", section:"BS on Answer", title:"Find the Smallest Divisor",        difficulty:"E", viz:"binarysearch", world:"Choosing a Divisor", hook:"Bigger divisor, smaller sum — monotonic again." },
    { id:"4-19", section:"BS on Answer", title:"Capacity to Ship Packages in D Days", difficulty:"M", viz:"binarysearch",  world:"Loading a Ship",     hook:"Search the capacity that just fits the deadline." },
    { id:"4-20", section:"BS on Answer", title:"Kth Missing Positive Number",      difficulty:"E", viz:"seats",        world:"Missing Tickets",    hook:"Missing count at an index is a searchable function." },
    { id:"4-21", section:"BS on Answer", title:"Aggressive Cows",                  difficulty:"H", viz:"canyon",       world:"Spacing the Stalls", hook:"Maximise the minimum gap." },
    { id:"4-22", section:"BS on Answer", title:"Book Allocation Problem",          difficulty:"H", viz:"binarysearch",     world:"Dividing the Reading", hook:"Minimise the largest share." },
    { id:"4-23", section:"BS on Answer", title:"Split Array — Largest Sum",        difficulty:"H", viz:"binarysearch",     world:"Fair Division",      hook:"Book allocation wearing a different name." },
    { id:"4-24", section:"BS on Answer", title:"Painter's Partition",              difficulty:"H", viz:"binarysearch",     world:"Painting a Fence",   hook:"The same minimise-the-maximum shape again." },
    { id:"4-25", section:"BS on Answer", title:"Minimise Maximum Distance between Gas Stations", difficulty:"H", viz:"canyon", world:"Refuelling Stops", hook:"A real-valued search space, not an integer one." },
    { id:"4-26", section:"BS on Answer", title:"Median of Two Sorted Arrays",      difficulty:"H", viz:"binarysearch", world:"Two Merged Queues",  hook:"Search the partition, not the merged array." },
    { id:"4-27", section:"BS on Answer", title:"Kth Element of Two Sorted Arrays", difficulty:"H", viz:"binarysearch", world:"Two Merged Queues",  hook:"The median problem, generalised to any k." },

    { id:"4-28", section:"BS on 2D",     title:"Find Row with Maximum 1s",         difficulty:"E", viz:"grid",     world:"Scanning a Grid",       hook:"Binary search each row's first 1." },
    { id:"4-29", section:"BS on 2D",     title:"Search in a 2D Matrix",            difficulty:"M", viz:"grid",     world:"Flattened Grid",        hook:"Treat the matrix as one long sorted array." },
    { id:"4-30", section:"BS on 2D",     title:"Search in a 2D Matrix II",         difficulty:"M", viz:"grid",     world:"Staircase Search",      hook:"Start at a corner where one move always helps." },
    { id:"4-31", section:"BS on 2D",     title:"Find Peak Element in 2D",          difficulty:"H", viz:"mountain", world:"Mountain Range",        hook:"Binary search the columns, scan the rows." },
    { id:"4-32", section:"BS on 2D",     title:"Median in a Row-wise Sorted Matrix", difficulty:"H", viz:"grid",   world:"Grid Median",           hook:"Search the value, count how many are smaller." },
  ]),

  S("Step 5", "Strings", [
    { id:"5-1",  section:"Basic",  title:"Remove Outermost Parentheses",     difficulty:"E", viz:"stackviz",    world:"Nested Boxes",          hook:"Depth tells you which brackets are decoration." },
    { id:"5-2",  section:"Basic",  title:"Reverse Words in a String",        difficulty:"M", viz:"mirror",      world:"Reordering a Sentence", hook:"Reverse everything, then reverse each word back." },
    { id:"5-3",  section:"Basic",  title:"Largest Odd Number in a String",   difficulty:"E", viz:"dna",         world:"Trimming Digits",       hook:"Scan from the right for the first odd digit." },
    { id:"5-4",  section:"Basic",  title:"Longest Common Prefix",            difficulty:"E", viz:"trie",        world:"Shared Road",           hook:"Walk together until the paths diverge." },
    { id:"5-5",  section:"Basic",  title:"Isomorphic Strings",               difficulty:"E", viz:"dedup",       world:"Substitution Cipher",   hook:"A consistent mapping in both directions." },
    { id:"5-6",  section:"Basic",  title:"Rotate String",                    difficulty:"E", viz:"carousel",    world:"Rotating Dial",         hook:"Any rotation is a substring of the doubled string." },
    { id:"5-7",  section:"Basic",  title:"Valid Anagram",                    difficulty:"E", viz:"votes",       world:"Letter Tally",          hook:"Same letters, same counts — order irrelevant." },

    { id:"5-8",  section:"Medium", title:"Sort Characters by Frequency",     difficulty:"M", viz:"leaderboard", world:"Popularity Chart",      hook:"Count, then sort the counts." },
    { id:"5-9",  section:"Medium", title:"Maximum Nesting Depth of Parentheses", difficulty:"E", viz:"stackviz", world:"Nested Boxes",         hook:"A running counter is all the stack you need." },
    { id:"5-10", section:"Medium", title:"Roman to Integer",                 difficulty:"E", viz:"terminal",    world:"Roman Numerals",        hook:"A smaller value before a bigger one subtracts." },
    { id:"5-11", section:"Medium", title:"Integer to Roman",                 difficulty:"M", viz:"terminal",    world:"Roman Numerals",        hook:"Greedy works here because the denominations allow it." },
    { id:"5-12", section:"Medium", title:"Implement Atoi",                   difficulty:"M", viz:"terminal",    world:"Parsing Input",         hook:"Every edge case is the actual problem." },
    { id:"5-13", section:"Medium", title:"Count Number of Substrings",       difficulty:"M", viz:"windowslide", world:"Window Counting",       hook:"Exactly-k equals at-most-k minus at-most-(k-1)." },
    { id:"5-14", section:"Medium", title:"Longest Palindromic Substring",    difficulty:"H", viz:"mirror",      world:"Mirror Centre",         hook:"Expand around every centre — 2n-1 of them." },
    { id:"5-15", section:"Medium", title:"Sum of Beauty of All Substrings",  difficulty:"M", viz:"votes",       world:"Letter Tally",          hook:"Maintain frequencies as the window grows." },
  ]),

  S("Step 6", "Linked List", [
    { id:"6-1",  section:"Learn 1D",  title:"Introduction to Linked List",       difficulty:"E", viz:"linkedlist", world:"Train Carriages",    hook:"Each carriage knows only the next one." },
    { id:"6-2",  section:"Learn 1D",  title:"Insert a Node",                     difficulty:"E", viz:"linkedlist", world:"Adding a Carriage",  hook:"Rewire two pointers, move nothing else." },
    { id:"6-3",  section:"Learn 1D",  title:"Delete a Node",                     difficulty:"E", viz:"linkedlist", world:"Uncoupling",         hook:"The predecessor is the one that matters." },
    { id:"6-4",  section:"Learn 1D",  title:"Find Length of Linked List",        difficulty:"E", viz:"linkedlist", world:"Counting Carriages", hook:"No index — you must walk it." },
    { id:"6-5",  section:"Learn 1D",  title:"Search an Element",                 difficulty:"E", viz:"linkedlist", world:"Walking the Train",  hook:"Linear, always — no jumping ahead." },

    { id:"6-6",  section:"Doubly LL", title:"Introduction to Doubly Linked List", difficulty:"E", viz:"linkedlist", world:"Two-Way Corridor",  hook:"Every link now points both ways." },
    { id:"6-7",  section:"Doubly LL", title:"Insert in a Doubly Linked List",    difficulty:"E", viz:"linkedlist", world:"Two-Way Corridor",   hook:"Four pointers to update, not two." },
    { id:"6-8",  section:"Doubly LL", title:"Delete in a Doubly Linked List",    difficulty:"E", viz:"linkedlist", world:"Two-Way Corridor",   hook:"No need to hunt for the predecessor." },
    { id:"6-9",  section:"Doubly LL", title:"Reverse a Doubly Linked List",      difficulty:"M", viz:"linkedlist", world:"Turning the Train",  hook:"Swap prev and next at every node." },

    { id:"6-10", section:"Medium",    title:"Middle of a Linked List",           difficulty:"E", viz:"linkedlist", world:"Two Runners",        hook:"Slow and fast — one arrives at half the distance." },
    { id:"6-11", section:"Medium",    title:"Reverse a Linked List (iterative)", difficulty:"E", viz:"linkedlist", world:"Flipping Couplings", hook:"Three pointers, one pass." },
    { id:"6-12", section:"Medium",    title:"Reverse a Linked List (recursive)", difficulty:"M", viz:"linkedlist", world:"Flipping Couplings", hook:"Reverse the tail, then fix the head." },
    { id:"6-13", section:"Medium",    title:"Detect a Loop in Linked List",      difficulty:"M", viz:"linkedlist", world:"Circular Track",     hook:"Two runners at different speeds must meet." },
    { id:"6-14", section:"Medium",    title:"Find Starting Point of Loop",       difficulty:"M", viz:"linkedlist", world:"Circular Track",     hook:"Reset one runner to the head, then walk in step." },
    { id:"6-15", section:"Medium",    title:"Length of Loop in Linked List",     difficulty:"M", viz:"linkedlist", world:"Circular Track",     hook:"Count one lap from the meeting point." },
    { id:"6-16", section:"Medium",    title:"Check if Linked List is Palindrome", difficulty:"M", viz:"mirror",    world:"Mirror Test",        hook:"Find the middle, reverse half, compare." },
    { id:"6-17", section:"Medium",    title:"Segregate Odd and Even Nodes",      difficulty:"M", viz:"twopointers",      world:"Splitting the Train", hook:"Two chains built in one pass, then joined." },
    { id:"6-18", section:"Medium",    title:"Remove Nth Node from End",          difficulty:"M", viz:"linkedlist", world:"Counting Backwards", hook:"A gap of n between two pointers." },
    { id:"6-19", section:"Medium",    title:"Delete the Middle Node",            difficulty:"M", viz:"linkedlist", world:"Uncoupling",         hook:"Stop the slow pointer one short of the middle." },
    { id:"6-20", section:"Medium",    title:"Sort a Linked List",                difficulty:"M", viz:"mergesort",  world:"Merging Piles",      hook:"Merge sort, because there is no random access." },
    { id:"6-21", section:"Medium",    title:"Sort a Linked List of 0s, 1s, 2s",  difficulty:"M", viz:"sorting",       world:"Dutch Flag",         hook:"Three chains, then stitch them together." },
    { id:"6-22", section:"Medium",    title:"Find Intersection Point of Y Lists", difficulty:"M", viz:"venn",      world:"Converging Tracks",  hook:"Swap heads at the end and the gap cancels out." },
    { id:"6-23", section:"Medium",    title:"Add 1 to a Number Represented as LL", difficulty:"M", viz:"linkedlist", world:"Odometer",         hook:"The carry has to travel backwards." },
    { id:"6-24", section:"Medium",    title:"Add Two Numbers as Linked Lists",   difficulty:"M", viz:"linkedlist", world:"Long Addition",      hook:"Carry propagation, node by node." },

    { id:"6-25", section:"Hard",      title:"Reverse Nodes in K Groups",         difficulty:"H", viz:"linkedlist", world:"Reversing Sections", hook:"Reverse a block, reattach, repeat." },
    { id:"6-26", section:"Hard",      title:"Rotate a Linked List",              difficulty:"M", viz:"carousel",   world:"Carousel",           hook:"Close the loop, then break it at the right place." },
    { id:"6-27", section:"Hard",      title:"Flatten a Linked List",             difficulty:"H", viz:"mergesort",  world:"Collapsing Layers",  hook:"Repeated merging of sorted sublists." },
    { id:"6-28", section:"Hard",      title:"Clone LL with Random Pointers",     difficulty:"H", viz:"dedup",      world:"Copying a Web",      hook:"Interleave copies so randoms resolve in O(1) space." },
  ]),

  S("Step 7", "Recursion", [
    { id:"7-1",  section:"Strong Hold",  title:"Recursive Implementation of atoi", difficulty:"H", viz:"fractal",  world:"Parsing Digits",      hook:"Peel one character, recurse on the rest." },
    { id:"7-2",  section:"Strong Hold",  title:"Pow(x, n)",                      difficulty:"M", viz:"fractal",   world:"Fast Exponentiation", hook:"Halve the exponent, square the result." },
    { id:"7-3",  section:"Strong Hold",  title:"Count Good Numbers",             difficulty:"E", viz:"fractal",   world:"Counting Patterns",   hook:"Fast power under a modulus." },
    { id:"7-4",  section:"Strong Hold",  title:"Sort a Stack Using Recursion",   difficulty:"M", viz:"stackviz",  world:"Restacking Plates",   hook:"Pop everything, insert on the way back." },
    { id:"7-5",  section:"Strong Hold",  title:"Reverse a Stack Using Recursion", difficulty:"M", viz:"stackviz", world:"Restacking Plates",   hook:"The call stack is your only extra storage." },

    { id:"7-6",  section:"Subsequences", title:"Generate All Binary Strings",    difficulty:"M", viz:"backtrack", world:"Branching Choices",   hook:"Two branches per position." },
    { id:"7-7",  section:"Subsequences", title:"Generate Parentheses",           difficulty:"M", viz:"backtrack", world:"Balanced Brackets",   hook:"Prune the moment the string can't be balanced." },
    { id:"7-8",  section:"Subsequences", title:"Print All Subsequences (Power Set)", difficulty:"M", viz:"backtrack", world:"Every Combination", hook:"Take it or leave it, at every index." },
    { id:"7-9",  section:"Subsequences", title:"Count Subsequences with Sum K",  difficulty:"E", viz:"backtrack", world:"Counting Paths",      hook:"Return counts instead of printing." },
    { id:"7-10", section:"Subsequences", title:"Check if Subsequence with Sum K Exists", difficulty:"M", viz:"backtrack", world:"Early Exit",   hook:"Stop the whole recursion on the first success." },
    { id:"7-11", section:"Subsequences", title:"Combination Sum",                difficulty:"M", viz:"backtrack", world:"Making Change",       hook:"Reuse allowed — don't advance the index." },
    { id:"7-12", section:"Subsequences", title:"Combination Sum II",             difficulty:"M", viz:"backtrack", world:"Making Change",       hook:"Skip duplicates at the same depth." },
    { id:"7-13", section:"Subsequences", title:"Subset Sum I",                   difficulty:"M", viz:"backtrack", world:"Every Subset",        hook:"All subset sums, in order of generation." },
    { id:"7-14", section:"Subsequences", title:"Subset Sum II",                  difficulty:"M", viz:"backtrack", world:"Every Subset",        hook:"Sort first so duplicates sit together." },
    { id:"7-15", section:"Subsequences", title:"Combination Sum III",            difficulty:"M", viz:"backtrack", world:"Fixed-Size Pick",     hook:"Two constraints to prune against." },
    { id:"7-16", section:"Subsequences", title:"Letter Combinations of a Phone Number", difficulty:"M", viz:"backtrack", world:"Old Keypad",   hook:"A branch per letter on each key." },

    { id:"7-17", section:"Hard",         title:"Palindrome Partitioning",        difficulty:"M", viz:"backtrack", world:"Cutting a String",    hook:"Cut only where the left piece is a palindrome." },
    { id:"7-18", section:"Hard",         title:"Word Search",                    difficulty:"M", viz:"maze",      world:"Word Grid",           hook:"Mark visited, recurse, then unmark." },
    { id:"7-19", section:"Hard",         title:"N Queens",                       difficulty:"H", viz:"chess",     world:"Chessboard",          hook:"Place, fail, take it back — backtracking you can watch." },
    { id:"7-20", section:"Hard",         title:"Rat in a Maze",                  difficulty:"H", viz:"maze",      world:"Maze Escape",         hook:"Four directions, one visited set." },
    { id:"7-21", section:"Hard",         title:"Word Break",                     difficulty:"M", viz:"backtrack", world:"Splitting Text",      hook:"Memoise or the branching kills you." },
    { id:"7-22", section:"Hard",         title:"M Coloring Problem",             difficulty:"H", viz:"graphs",    world:"Map Colouring",       hook:"Check neighbours before committing a colour." },
    { id:"7-23", section:"Hard",         title:"Sudoku Solver",                  difficulty:"H", viz:"grid",      world:"Sudoku",              hook:"Constraint propagation plus backtracking." },
    { id:"7-24", section:"Hard",         title:"Expression Add Operators",       difficulty:"H", viz:"backtrack", world:"Building Equations",  hook:"Multiplication forces you to track the last operand." },
  ]),

  S("Step 8", "Bit Manipulation", [
    { id:"8-1",  section:"Learn",     title:"Introduction to Bit Manipulation", difficulty:"E", viz:"circuit",    world:"Row of Switches",    hook:"Every integer is a row of on/off switches." },
    { id:"8-2",  section:"Learn",     title:"Check if i-th Bit is Set",         difficulty:"E", viz:"circuit",    world:"Reading a Switch",   hook:"Shift a mask into position and AND." },
    { id:"8-3",  section:"Learn",     title:"Swap Two Numbers Without Temp",    difficulty:"E", viz:"circuit",    world:"Swapping Wires",     hook:"XOR is its own inverse." },
    { id:"8-4",  section:"Learn",     title:"Check if a Number is Power of 2",  difficulty:"E", viz:"circuit",    world:"Single Switch",      hook:"Exactly one bit set — n & (n-1) proves it." },
    { id:"8-5",  section:"Learn",     title:"Count Set Bits",                   difficulty:"E", viz:"circuit",    world:"Counting Switches",  hook:"Brian Kernighan's trick clears the lowest set bit." },
    { id:"8-6",  section:"Learn",     title:"Set / Clear / Toggle the i-th Bit", difficulty:"E", viz:"circuit",   world:"Flipping Switches",  hook:"OR to set, AND-NOT to clear, XOR to toggle." },
    { id:"8-7",  section:"Learn",     title:"Remove the Last Set Bit",          difficulty:"E", viz:"circuit",    world:"Turning One Off",    hook:"n & (n-1) — the foundation of several tricks." },

    { id:"8-8",  section:"Interview", title:"Single Number I",                  difficulty:"E", viz:"particles",  world:"The Odd One Out",    hook:"XOR cancels every pair." },
    { id:"8-9",  section:"Interview", title:"Single Number II (others thrice)", difficulty:"M", viz:"circuit",    world:"Counting in Threes", hook:"Count each bit position mod 3." },
    { id:"8-10", section:"Interview", title:"Single Number III (two loners)",   difficulty:"M", viz:"circuit",    world:"Two Odd Ones",       hook:"A differing bit splits them into two groups." },
    { id:"8-11", section:"Interview", title:"XOR of Numbers in a Range",        difficulty:"M", viz:"circuit",    world:"Parity Pattern",     hook:"The prefix XOR repeats with period 4." },
    { id:"8-12", section:"Interview", title:"Divide Two Integers Without Division", difficulty:"M", viz:"circuit", world:"Long Division",     hook:"Subtract shifted multiples — binary long division." },
    { id:"8-13", section:"Interview", title:"Minimum Bit Flips to Convert",     difficulty:"E", viz:"circuit",    world:"Matching Switches",  hook:"XOR then count the set bits." },
    { id:"8-14", section:"Interview", title:"Power Set Using Bitmasks",         difficulty:"M", viz:"backtrack",  world:"Every Subset",       hook:"Each integer 0..2^n-1 names a subset." },

    { id:"8-15", section:"Maths",     title:"Count Primes (Sieve)",             difficulty:"M", viz:"searchbeam", world:"Prime Sieve",        hook:"Strike out the multiples; the primes are what's left." },
    { id:"8-16", section:"Maths",     title:"Prime Factorisation Using Sieve",  difficulty:"M", viz:"searchbeam", world:"Smallest Factor",    hook:"Precompute the smallest prime factor once." },
    { id:"8-17", section:"Maths",     title:"Power Exponentiation",             difficulty:"M", viz:"fractal",    world:"Fast Power",         hook:"Square and halve — O(log n) multiplications." },
  ]),

  S("Step 9", "Stacks and Queues", [
    { id:"9-1",  section:"Learning",  title:"Implement Stack Using Array",      difficulty:"E", viz:"stackviz",   world:"Plate Stack",        hook:"One index is the entire data structure." },
    { id:"9-2",  section:"Learning",  title:"Implement Queue Using Array",      difficulty:"E", viz:"stackviz",   world:"Ticket Queue",       hook:"Two indices, wrapped around." },
    { id:"9-3",  section:"Learning",  title:"Implement Stack Using Queue",      difficulty:"M", viz:"stackviz",   world:"Reversing a Line",   hook:"Rotate the queue after every push." },
    { id:"9-4",  section:"Learning",  title:"Implement Queue Using Stack",      difficulty:"M", viz:"stackviz",   world:"Two Plate Stacks",   hook:"Amortised O(1) — each item moves at most twice." },
    { id:"9-5",  section:"Learning",  title:"Implement Stack Using Linked List", difficulty:"E", viz:"linkedlist", world:"Chain of Plates",   hook:"Push and pop both at the head." },
    { id:"9-6",  section:"Learning",  title:"Implement Queue Using Linked List", difficulty:"E", viz:"linkedlist", world:"Chain of Tickets",  hook:"Head to dequeue, tail to enqueue." },
    { id:"9-7",  section:"Learning",  title:"Balanced Parentheses",             difficulty:"E", viz:"stackviz",   world:"Nested Boxes",       hook:"The stack remembers what's still open." },
    { id:"9-8",  section:"Learning",  title:"Implement Min Stack",              difficulty:"M", viz:"stackviz",   world:"Plate Stack",        hook:"Store the running minimum alongside each value." },

    { id:"9-9",  section:"Notation",  title:"Infix to Postfix Conversion",      difficulty:"M", viz:"stackviz",   world:"Rewriting Formulae", hook:"Operator precedence drives the stack." },
    { id:"9-10", section:"Notation",  title:"Prefix to Infix Conversion",       difficulty:"M", viz:"stackviz",   world:"Rewriting Formulae", hook:"Scan right to left, rebuild as you go." },
    { id:"9-11", section:"Notation",  title:"Postfix to Infix Conversion",      difficulty:"M", viz:"stackviz",   world:"Rewriting Formulae", hook:"Pop two, wrap in brackets, push back." },
    { id:"9-12", section:"Notation",  title:"Evaluate Postfix Expression",      difficulty:"M", viz:"stackviz",   world:"Calculator",         hook:"No brackets needed — the order is already fixed." },

    { id:"9-13", section:"Monotonic", title:"Next Greater Element",             difficulty:"M", viz:"stackviz",   world:"Taller Neighbour",   hook:"Who is the first taller person to your right?" },
    { id:"9-14", section:"Monotonic", title:"Next Greater Element II (circular)", difficulty:"M", viz:"carousel", world:"Circular Queue",     hook:"Walk the array twice to fake the wraparound." },
    { id:"9-15", section:"Monotonic", title:"Next Smaller Element",             difficulty:"E", viz:"stackviz",   world:"Shorter Neighbour",  hook:"The same stack, flipped comparison." },
    { id:"9-16", section:"Monotonic", title:"Number of NGEs to the Right",      difficulty:"M", viz:"stackviz",   world:"Counting Taller",    hook:"Offline queries answered in one sweep." },
    { id:"9-17", section:"Monotonic", title:"Trapping Rainwater",               difficulty:"H", viz:"mountain",   world:"Rainwater Basin",    hook:"Water above a bar is bounded by the smaller wall." },
    { id:"9-18", section:"Monotonic", title:"Sum of Subarray Minimums",         difficulty:"M", viz:"stackviz",   world:"Counting Spans",     hook:"Each element's span of dominance, counted once." },
    { id:"9-19", section:"Monotonic", title:"Asteroid Collision",               difficulty:"M", viz:"particles",  world:"Asteroid Belt",      hook:"The stack models survivors of each collision." },
    { id:"9-20", section:"Monotonic", title:"Sum of Subarray Ranges",           difficulty:"M", viz:"stackviz",   world:"Counting Spans",     hook:"Maximums minus minimums, both by the same trick." },
    { id:"9-21", section:"Monotonic", title:"Remove K Digits",                  difficulty:"M", viz:"stackviz",   world:"Trimming a Number",  hook:"Greedily drop any digit bigger than its successor." },
    { id:"9-22", section:"Monotonic", title:"Largest Rectangle in Histogram",   difficulty:"H", viz:"mountain",   world:"Skyline",            hook:"Each bar's widest span where it is the shortest." },
    { id:"9-23", section:"Monotonic", title:"Maximal Rectangle",                difficulty:"H", viz:"grid",       world:"Skyline Grid",       hook:"A histogram problem repeated per row." },

    { id:"9-24", section:"Implement", title:"Sliding Window Maximum",           difficulty:"H", viz:"windowslide", world:"Moving Window",     hook:"A deque holding only useful candidates." },
    { id:"9-25", section:"Implement", title:"Stock Span Problem",               difficulty:"M", viz:"stockchart",  world:"Stock Streak",      hook:"How many days back was it never higher?" },
    { id:"9-26", section:"Implement", title:"Celebrity Problem",                difficulty:"M", viz:"social",      world:"The Celebrity",     hook:"Every question eliminates one candidate." },
    { id:"9-27", section:"Implement", title:"LRU Cache",                        difficulty:"H", viz:"linkedlist",  world:"Cache Eviction",    hook:"A hash map plus a doubly linked list." },
    { id:"9-28", section:"Implement", title:"LFU Cache",                        difficulty:"H", viz:"linkedlist",  world:"Cache Eviction",    hook:"Frequency buckets, each an ordered list." },
  ]),

  S("Step 10", "Sliding Window & Two Pointer", [
    { id:"10-1",  section:"Medium", title:"Longest Substring Without Repeating Characters", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"Shrink from the left the moment a repeat appears." },
    { id:"10-2",  section:"Medium", title:"Max Consecutive Ones III",           difficulty:"M", viz:"windowslide", world:"Sliding Window",    hook:"The window is valid while flips used ≤ k." },
    { id:"10-3",  section:"Medium", title:"Fruit Into Baskets",                 difficulty:"M", viz:"windowslide", world:"Two Baskets",       hook:"At most two distinct kinds in the window." },
    { id:"10-4",  section:"Medium", title:"Longest Repeating Character Replacement", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"Window length minus the most frequent letter." },
    { id:"10-5",  section:"Medium", title:"Binary Subarrays With Sum",          difficulty:"M", viz:"windowslide", world:"Window Counting",   hook:"Exactly-k as a difference of two at-most-k runs." },
    { id:"10-6",  section:"Medium", title:"Count Nice Subarrays",               difficulty:"M", viz:"windowslide", world:"Window Counting",   hook:"Odd numbers behave like 1s in a binary array." },
    { id:"10-7",  section:"Medium", title:"Number of Substrings Containing All Three Characters", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"Count by last-seen positions." },
    { id:"10-8",  section:"Medium", title:"Maximum Points You Can Obtain from Cards", difficulty:"M", viz:"cards",  world:"Cards from Both Ends", hook:"A fixed window on the wrap-around." },

    { id:"10-9",  section:"Hard",   title:"Longest Substring with At Most K Distinct Characters", difficulty:"M", viz:"windowslide", world:"Sliding Window", hook:"A frequency map decides when to shrink." },
    { id:"10-10", section:"Hard",   title:"Subarrays with K Different Integers", difficulty:"H", viz:"windowslide", world:"Window Counting",  hook:"The at-most-k difference trick again." },
    { id:"10-11", section:"Hard",   title:"Minimum Window Substring",           difficulty:"H", viz:"windowslide", world:"Shrinking Window",  hook:"Expand until valid, then shrink while it stays valid." },
    { id:"10-12", section:"Hard",   title:"Minimum Window Subsequence",         difficulty:"H", viz:"windowslide", world:"Shrinking Window",  hook:"Order matters here — not just membership." },
  ]),

  S("Step 11", "Heaps", [
    { id:"11-1",  section:"Learning", title:"Introduction to Priority Queue",   difficulty:"E", viz:"heapviz",    world:"Triage Queue",       hook:"The most urgent always rises to the top." },
    { id:"11-2",  section:"Learning", title:"Min Heap and Max Heap Implementation", difficulty:"M", viz:"heapviz", world:"Triage Queue",      hook:"A complete tree stored as a flat array." },
    { id:"11-3",  section:"Learning", title:"Check if an Array Represents a Heap", difficulty:"E", viz:"heapviz", world:"Triage Audit",       hook:"Every parent versus its two children." },
    { id:"11-4",  section:"Learning", title:"Convert Min Heap to Max Heap",     difficulty:"E", viz:"heapviz",    world:"Reversing Priority", hook:"Heapify from the last parent backwards." },

    { id:"11-5",  section:"Medium",   title:"Kth Largest Element in an Array",  difficulty:"M", viz:"heapviz",    world:"Top-K Leaderboard",  hook:"A size-k min-heap beats a full sort." },
    { id:"11-6",  section:"Medium",   title:"Kth Smallest Element in an Array", difficulty:"M", viz:"heapviz",    world:"Bottom-K",           hook:"The same idea with the comparison flipped." },
    { id:"11-7",  section:"Medium",   title:"Sort K Sorted (Nearly Sorted) Array", difficulty:"M", viz:"heapviz", world:"Almost in Order",    hook:"A heap of size k+1 is enough." },
    { id:"11-8",  section:"Medium",   title:"Merge M Sorted Lists",             difficulty:"H", viz:"mergesort",  world:"Merging Queues",     hook:"A heap of list heads picks the next value." },
    { id:"11-9",  section:"Medium",   title:"Replace Elements by Rank in Array", difficulty:"E", viz:"leaderboard", world:"Ranking",          hook:"Sort once, map back by value." },
    { id:"11-10", section:"Medium",   title:"Task Scheduler",                   difficulty:"M", viz:"timeline",   world:"Cooling Periods",    hook:"The most frequent task sets the schedule length." },
    { id:"11-11", section:"Medium",   title:"Hands of Straights",               difficulty:"M", viz:"cards",      world:"Dealing Runs",       hook:"Always start a group from the smallest card left." },

    { id:"11-12", section:"Hard",     title:"Design Twitter",                   difficulty:"M", viz:"social",     world:"Feed Assembly",      hook:"Merge the k most recent from each followee." },
    { id:"11-13", section:"Hard",     title:"Connect N Ropes with Minimum Cost", difficulty:"E", viz:"heapviz",   world:"Joining Ropes",      hook:"Always join the two shortest — Huffman's insight." },
    { id:"11-14", section:"Hard",     title:"Kth Largest Element in a Stream",  difficulty:"E", viz:"heapviz",    world:"Live Leaderboard",   hook:"Keep exactly k in the heap, discard the rest." },
    { id:"11-15", section:"Hard",     title:"Maximum Sum Combination",          difficulty:"M", viz:"heapviz",    world:"Best Pairings",      hook:"Explore the frontier, not the full grid." },
    { id:"11-16", section:"Hard",     title:"Find Median from Data Stream",     difficulty:"H", viz:"balance",    world:"Balanced Scales",    hook:"Two heaps, kept the same size." },
    { id:"11-17", section:"Hard",     title:"K Most Frequent Elements",         difficulty:"M", viz:"leaderboard", world:"Top Charts",        hook:"Count, then heap or bucket by frequency." },
  ]),

  S("Step 12", "Greedy Algorithms", [
    { id:"12-1",  section:"Easy",        title:"Assign Cookies",               difficulty:"E", viz:"balance",     world:"Matching Sizes",     hook:"Sort both sides and pair greedily." },
    { id:"12-2",  section:"Easy",        title:"Fractional Knapsack",          difficulty:"M", viz:"vault",       world:"Loading a Truck",    hook:"Best value-per-weight first — fractions make greedy safe." },
    { id:"12-3",  section:"Easy",        title:"Minimum Coins (Greedy)",       difficulty:"E", viz:"vault",       world:"Cash Drawer",        hook:"Works for real currency, fails in general." },
    { id:"12-4",  section:"Easy",        title:"Lemonade Change",              difficulty:"E", viz:"vault",       world:"Making Change",      hook:"Spend the largest notes you can afford to." },
    { id:"12-5",  section:"Easy",        title:"Valid Parenthesis String",     difficulty:"M", viz:"stackviz",    world:"Flexible Brackets",  hook:"Track a range of possible open counts." },

    { id:"12-6",  section:"Medium/Hard", title:"N Meetings in One Room",       difficulty:"E", viz:"timeline",    world:"Room Booking",       hook:"Sort by finish time, not start time." },
    { id:"12-7",  section:"Medium/Hard", title:"Jump Game",                    difficulty:"M", viz:"canyon",      world:"Crossing Gaps",      hook:"Track the furthest reachable index." },
    { id:"12-8",  section:"Medium/Hard", title:"Jump Game II",                 difficulty:"M", viz:"canyon",      world:"Crossing Gaps",      hook:"Jump only when the current range runs out." },
    { id:"12-9",  section:"Medium/Hard", title:"Minimum Platforms",            difficulty:"M", viz:"timeline",    world:"Train Platforms",    hook:"Sort arrivals and departures separately." },
    { id:"12-10", section:"Medium/Hard", title:"Job Sequencing Problem",       difficulty:"M", viz:"timeline",    world:"Deadline Scheduling", hook:"Place each job as late as its deadline allows." },
    { id:"12-11", section:"Medium/Hard", title:"Candy",                        difficulty:"H", viz:"leaderboard", world:"Fair Rewards",       hook:"Two passes — left to right, then right to left." },
    { id:"12-12", section:"Medium/Hard", title:"Shortest Job First",           difficulty:"E", viz:"timeline",    world:"CPU Scheduling",     hook:"Shortest first minimises average wait." },
    { id:"12-13", section:"Medium/Hard", title:"Insert Interval",              difficulty:"M", viz:"timeline",    world:"Calendar Insert",    hook:"Three phases: before, overlapping, after." },
    { id:"12-14", section:"Medium/Hard", title:"Merge Intervals",              difficulty:"M", viz:"timeline",    world:"Calendar Merge",     hook:"Sort by start and the overlaps fall out in one pass." },
    { id:"12-15", section:"Medium/Hard", title:"Non-overlapping Intervals",    difficulty:"M", viz:"timeline",    world:"Dropping Conflicts", hook:"Keep the most meetings by ending earliest." },
  ]),

  S("Step 13", "Binary Trees", [
    { id:"13-1",  section:"Traversals", title:"Introduction to Trees",         difficulty:"E", viz:"treeviz",  world:"Family Tree",           hook:"One root, and every node a smaller tree." },
    { id:"13-2",  section:"Traversals", title:"Binary Tree Representation",    difficulty:"E", viz:"treeviz",  world:"Family Tree",           hook:"Nodes and pointers, or a flat array." },
    { id:"13-3",  section:"Traversals", title:"Preorder Traversal",            difficulty:"E", viz:"treeviz",  world:"Walking the Tree",      hook:"Root first — how you'd copy a tree." },
    { id:"13-4",  section:"Traversals", title:"Inorder Traversal",             difficulty:"E", viz:"treeviz",  world:"Walking the Tree",      hook:"On a BST this comes out sorted." },
    { id:"13-5",  section:"Traversals", title:"Postorder Traversal",           difficulty:"E", viz:"treeviz",  world:"Walking the Tree",      hook:"Children first — how you'd delete a tree." },
    { id:"13-6",  section:"Traversals", title:"Level Order Traversal",         difficulty:"M", viz:"bfs",      world:"Floor by Floor",        hook:"A queue turns depth into breadth." },
    { id:"13-7",  section:"Traversals", title:"Iterative Preorder",            difficulty:"M", viz:"stackviz", world:"Manual Stack",          hook:"Push right before left." },
    { id:"13-8",  section:"Traversals", title:"Iterative Inorder",             difficulty:"M", viz:"stackviz", world:"Manual Stack",          hook:"Dive left, pop, then go right." },
    { id:"13-9",  section:"Traversals", title:"Iterative Postorder (2 stacks)", difficulty:"M", viz:"stackviz", world:"Manual Stack",         hook:"Reverse of a modified preorder." },
    { id:"13-10", section:"Traversals", title:"Preorder, Inorder, Postorder in One Traversal", difficulty:"M", viz:"treeviz", world:"One Walk, Three Orders", hook:"A state counter per stack frame." },

    { id:"13-11", section:"Medium",     title:"Height of a Binary Tree",       difficulty:"M", viz:"treeviz",  world:"Measuring Depth",       hook:"One plus the taller child." },
    { id:"13-12", section:"Medium",     title:"Check if Tree is Balanced",     difficulty:"M", viz:"balance",  world:"Balanced Scales",       hook:"Return height and validity together." },
    { id:"13-13", section:"Medium",     title:"Diameter of a Binary Tree",     difficulty:"M", viz:"treeviz",  world:"Longest Path",          hook:"The answer may not pass through the root." },
    { id:"13-14", section:"Medium",     title:"Maximum Path Sum",              difficulty:"H", viz:"treeviz",  world:"Best Route",            hook:"Return the best arm, record the best arch." },
    { id:"13-15", section:"Medium",     title:"Check if Two Trees are Identical", difficulty:"M", viz:"mirror", world:"Spot the Difference",  hook:"Structure and values, in lockstep." },
    { id:"13-16", section:"Medium",     title:"Zig Zag Traversal",             difficulty:"M", viz:"bfs",      world:"Snaking Levels",        hook:"Alternate the direction each level." },
    { id:"13-17", section:"Medium",     title:"Boundary Traversal",            difficulty:"M", viz:"treeviz",  world:"Tracing the Edge",      hook:"Left edge, leaves, right edge reversed." },
    { id:"13-18", section:"Medium",     title:"Vertical Order Traversal",      difficulty:"M", viz:"grid",     world:"Column View",           hook:"Sort by column, then row, then value." },
    { id:"13-19", section:"Medium",     title:"Top View of Binary Tree",       difficulty:"M", viz:"treeviz",  world:"Bird's Eye",            hook:"First node seen in each column." },
    { id:"13-20", section:"Medium",     title:"Bottom View of Binary Tree",    difficulty:"M", viz:"treeviz",  world:"Worm's Eye",            hook:"Last node seen in each column." },
    { id:"13-21", section:"Medium",     title:"Right / Left View of Binary Tree", difficulty:"M", viz:"treeviz", world:"Side View",           hook:"First node encountered per level." },
    { id:"13-22", section:"Medium",     title:"Symmetric Binary Tree",         difficulty:"M", viz:"mirror",   world:"Mirror Test",           hook:"Compare outer with outer, inner with inner." },

    { id:"13-23", section:"Hard",       title:"Root to Node Path",             difficulty:"M", viz:"treeviz",  world:"Tracing Ancestry",      hook:"Build the path on the way down, pop on failure." },
    { id:"13-24", section:"Hard",       title:"Lowest Common Ancestor",        difficulty:"M", viz:"treeviz",  world:"Common Ancestor",       hook:"The node where the two searches diverge." },
    { id:"13-25", section:"Hard",       title:"Maximum Width of Binary Tree",  difficulty:"M", viz:"bfs",      world:"Widest Floor",          hook:"Index nodes as if the tree were complete." },
    { id:"13-26", section:"Hard",       title:"Children Sum Property",         difficulty:"H", viz:"treeviz",  world:"Balancing Sums",        hook:"Push values down, then fix on the way back." },
    { id:"13-27", section:"Hard",       title:"All Nodes at Distance K",       difficulty:"M", viz:"bfs",      world:"Blast Radius",          hook:"Add parent links and it becomes a graph BFS." },
    { id:"13-28", section:"Hard",       title:"Minimum Time to Burn the Tree", difficulty:"H", viz:"bfs",      world:"Spreading Fire",        hook:"BFS outward from the ignition node." },
    { id:"13-29", section:"Hard",       title:"Count Total Nodes in Complete Tree", difficulty:"M", viz:"treeviz", world:"Counting Fast",      hook:"Compare left and right heights to skip subtrees." },
    { id:"13-30", section:"Hard",       title:"Construct Tree from Preorder and Inorder", difficulty:"H", viz:"treeviz", world:"Rebuilding",   hook:"Preorder names the root; inorder splits the sides." },
    { id:"13-31", section:"Hard",       title:"Construct Tree from Postorder and Inorder", difficulty:"H", viz:"treeviz", world:"Rebuilding",  hook:"Read postorder backwards for the same trick." },
    { id:"13-32", section:"Hard",       title:"Serialize and Deserialize Binary Tree", difficulty:"H", viz:"treeviz", world:"Saving a Tree",  hook:"Nulls must be recorded or the shape is lost." },
    { id:"13-33", section:"Hard",       title:"Morris Preorder Traversal",     difficulty:"M", viz:"treeviz",  world:"No Stack Needed",       hook:"Temporary threads replace the call stack." },
    { id:"13-34", section:"Hard",       title:"Morris Inorder Traversal",      difficulty:"M", viz:"treeviz",  world:"No Stack Needed",       hook:"O(1) space, by rewiring and restoring." },
    { id:"13-35", section:"Hard",       title:"Flatten Binary Tree to Linked List", difficulty:"H", viz:"linkedlist", world:"Uncoiling",       hook:"Right-skewed, in preorder." },
  ]),

  S("Step 14", "Binary Search Trees", [
    { id:"14-1",  section:"Concepts", title:"Introduction to Binary Search Tree", difficulty:"E", viz:"bst",     world:"Filing Cabinet",      hook:"Left is smaller, right is bigger — always." },
    { id:"14-2",  section:"Concepts", title:"Search in a BST",                 difficulty:"E", viz:"bst",        world:"Filing Cabinet",      hook:"Each comparison discards a whole subtree." },
    { id:"14-3",  section:"Concepts", title:"Find Min/Max in BST",             difficulty:"E", viz:"bst",        world:"Filing Cabinet",      hook:"Walk as far left or right as you can." },
    { id:"14-4",  section:"Concepts", title:"Ceil in a BST",                   difficulty:"E", viz:"bst",        world:"Nearest Above",       hook:"Remember the last left turn you took." },
    { id:"14-5",  section:"Concepts", title:"Floor in a BST",                  difficulty:"E", viz:"bst",        world:"Nearest Below",       hook:"Remember the last right turn you took." },
    { id:"14-6",  section:"Concepts", title:"Insert a Node in BST",            difficulty:"E", viz:"bst",        world:"Filing a Folder",     hook:"Every value finds its own branch." },
    { id:"14-7",  section:"Concepts", title:"Delete a Node in BST",            difficulty:"M", viz:"bst",        world:"Filing Cabinet Reshuffle", hook:"Three cases — the two-child one needs a successor." },
    { id:"14-8",  section:"Concepts", title:"Kth Smallest / Largest in BST",   difficulty:"M", viz:"bst",        world:"Ranked Lookup",       hook:"Inorder is sorted, so just count." },
    { id:"14-9",  section:"Concepts", title:"Check if a Tree is a Valid BST",  difficulty:"M", viz:"bst",        world:"Auditing Order",      hook:"Every node needs a range, not just a parent check." },

    { id:"14-10", section:"Practice", title:"LCA in a Binary Search Tree",     difficulty:"M", viz:"bst",        world:"Common Ancestor",     hook:"The first node between the two values." },
    { id:"14-11", section:"Practice", title:"Construct BST from Preorder",     difficulty:"M", viz:"bst",        world:"Rebuilding",          hook:"Upper bounds make it a single pass." },
    { id:"14-12", section:"Practice", title:"Inorder Successor / Predecessor", difficulty:"M", viz:"bst",        world:"Next in Order",       hook:"Right subtree's minimum, or the last left turn." },
    { id:"14-13", section:"Practice", title:"BST Iterator",                    difficulty:"M", viz:"stackviz",   world:"Lazy Walk",           hook:"A stack holding only the current left spine." },
    { id:"14-14", section:"Practice", title:"Two Sum in a BST",                difficulty:"M", viz:"twopointers", world:"Pair Lookup",        hook:"Two iterators, one from each end." },
    { id:"14-15", section:"Practice", title:"Recover BST (two swapped nodes)", difficulty:"H", viz:"bst",        world:"Fixing the Order",    hook:"Inorder reveals exactly two violations." },
    { id:"14-16", section:"Practice", title:"Largest BST in a Binary Tree",    difficulty:"H", viz:"bst",        world:"Finding Order",       hook:"Return size, min and max from every subtree." },
  ]),

  S("Step 15", "Graphs", [
    { id:"15-1",  section:"Learning",      title:"Graph and Its Types",        difficulty:"E", viz:"graphs",   world:"Road Network",         hook:"Nodes and edges — the shape of almost everything." },
    { id:"15-2",  section:"Learning",      title:"Graph Representation",       difficulty:"E", viz:"graphs",   world:"Map or Table",         hook:"Adjacency list or matrix — density decides." },
    { id:"15-3",  section:"Learning",      title:"Connected Components",       difficulty:"M", viz:"graphs",   world:"Separate Islands",     hook:"One traversal per unvisited starting node." },
    { id:"15-4",  section:"Learning",      title:"BFS of Graph",               difficulty:"M", viz:"bfs",      world:"Friend Discovery",     hook:"Explore the network level by level." },
    { id:"15-5",  section:"Learning",      title:"DFS of Graph",               difficulty:"M", viz:"dfs",      world:"Maze Exploration",     hook:"Dive deep, backtrack, map every corridor." },

    { id:"15-6",  section:"Traversal",     title:"Number of Provinces",        difficulty:"M", viz:"graphs",   world:"Separate Islands",     hook:"Counting connected components by another name." },
    { id:"15-7",  section:"Traversal",     title:"Number of Islands",          difficulty:"M", viz:"grid",     world:"Island Counting",      hook:"A grid is a graph with implicit edges." },
    { id:"15-8",  section:"Traversal",     title:"Flood Fill",                 difficulty:"E", viz:"grid",     world:"Paint Bucket",         hook:"The fill tool in every image editor." },
    { id:"15-9",  section:"Traversal",     title:"Rotten Oranges",             difficulty:"M", viz:"grid",     world:"Spreading Rot",        hook:"Multi-source BFS measures time, not distance." },
    { id:"15-10", section:"Traversal",     title:"Detect Cycle in Undirected Graph (BFS)", difficulty:"M", viz:"graphs", world:"Circular Route", hook:"A visited neighbour that isn't the parent." },
    { id:"15-11", section:"Traversal",     title:"Detect Cycle in Undirected Graph (DFS)", difficulty:"M", viz:"dfs", world:"Circular Route",  hook:"The same test, carried down the recursion." },
    { id:"15-12", section:"Traversal",     title:"Distance of Nearest Cell Having 1", difficulty:"M", viz:"grid", world:"Nearest Source",    hook:"Start BFS from every source at once." },
    { id:"15-13", section:"Traversal",     title:"Surrounded Regions",         difficulty:"M", viz:"grid",     world:"Capturing Territory",  hook:"Work from the border inwards." },
    { id:"15-14", section:"Traversal",     title:"Number of Enclaves",         difficulty:"M", viz:"grid",     world:"Landlocked",           hook:"Anything reachable from the edge escapes." },
    { id:"15-15", section:"Traversal",     title:"Word Ladder I",              difficulty:"H", viz:"bfs",      world:"Word Chain",           hook:"Words are nodes; one-letter edits are edges." },
    { id:"15-16", section:"Traversal",     title:"Word Ladder II",             difficulty:"H", viz:"bfs",      world:"Word Chain",           hook:"BFS for distance, then backtrack every shortest path." },
    { id:"15-17", section:"Traversal",     title:"Bipartite Graph Check",      difficulty:"M", viz:"graphs",   world:"Two Teams",            hook:"Two-colour it; a clash means an odd cycle." },
    { id:"15-18", section:"Traversal",     title:"Detect Cycle in Directed Graph", difficulty:"H", viz:"dfs",  world:"Circular Dependency",  hook:"A back edge to a node still on the stack." },

    { id:"15-19", section:"Topo Sort",     title:"Topological Sort (DFS)",     difficulty:"M", viz:"dfs",      world:"Build Order",          hook:"Finish times, reversed." },
    { id:"15-20", section:"Topo Sort",     title:"Kahn's Algorithm (BFS Topo Sort)", difficulty:"M", viz:"bfs", world:"Task Scheduling",     hook:"Nothing starts before its prerequisite." },
    { id:"15-21", section:"Topo Sort",     title:"Course Schedule I",          difficulty:"M", viz:"graphs",   world:"Prerequisites",        hook:"A valid order exists only without cycles." },
    { id:"15-22", section:"Topo Sort",     title:"Course Schedule II",         difficulty:"M", viz:"graphs",   world:"Prerequisites",        hook:"Return the order, not just whether one exists." },
    { id:"15-23", section:"Topo Sort",     title:"Find Eventual Safe States",  difficulty:"M", viz:"graphs",   world:"Safe Ground",          hook:"Reverse the edges and run Kahn's." },
    { id:"15-24", section:"Topo Sort",     title:"Alien Dictionary",           difficulty:"H", viz:"graphs",   world:"Unknown Alphabet",     hook:"Derive the edges from adjacent word pairs." },

    { id:"15-25", section:"Shortest Path", title:"Shortest Path in UG with Unit Weights", difficulty:"M", viz:"bfs", world:"Fewest Hops",    hook:"Unit weights mean BFS is already optimal." },
    { id:"15-26", section:"Shortest Path", title:"Shortest Path in DAG",       difficulty:"M", viz:"graphs",   world:"One-Way Streets",      hook:"Topological order removes the need for a heap." },
    { id:"15-27", section:"Shortest Path", title:"Dijkstra's Algorithm",       difficulty:"M", viz:"dijkstra", world:"GPS Navigation",       hook:"Always expand the cheapest frontier first." },
    { id:"15-28", section:"Shortest Path", title:"Shortest Path in Binary Maze", difficulty:"M", viz:"maze",   world:"Maze Escape",          hook:"BFS on a grid with obstacles." },
    { id:"15-29", section:"Shortest Path", title:"Path with Minimum Effort",   difficulty:"M", viz:"mountain", world:"Gentlest Climb",       hook:"Minimise the largest single step." },
    { id:"15-30", section:"Shortest Path", title:"Cheapest Flights Within K Stops", difficulty:"M", viz:"graphs", world:"Connecting Flights", hook:"Stops bound the relaxation rounds." },
    { id:"15-31", section:"Shortest Path", title:"Network Delay Time",         difficulty:"M", viz:"dijkstra", world:"Signal Spread",        hook:"The slowest destination sets the answer." },
    { id:"15-32", section:"Shortest Path", title:"Number of Ways to Arrive at Destination", difficulty:"M", viz:"dijkstra", world:"Counting Routes", hook:"Carry a path count alongside the distance." },
    { id:"15-33", section:"Shortest Path", title:"Bellman-Ford Algorithm",     difficulty:"H", viz:"graphs",   world:"Currency Arbitrage",   hook:"Handles negative weights, and detects negative cycles." },
    { id:"15-34", section:"Shortest Path", title:"Floyd-Warshall Algorithm",   difficulty:"H", viz:"grid",     world:"All-Pairs Table",      hook:"Try every node as an intermediate." },
    { id:"15-35", section:"Shortest Path", title:"Find the City With Smallest Number of Neighbours", difficulty:"M", viz:"grid", world:"All-Pairs Table", hook:"Floyd-Warshall, then read the rows." },

    { id:"15-36", section:"MST & DSU",     title:"Minimum Spanning Tree Theory", difficulty:"M", viz:"powerline", world:"Wiring a Town",     hook:"Connect everything for the least cable." },
    { id:"15-37", section:"MST & DSU",     title:"Prim's Algorithm",           difficulty:"M", viz:"powerline", world:"Wiring a Town",       hook:"Grow one tree, always taking the cheapest edge out." },
    { id:"15-38", section:"MST & DSU",     title:"Disjoint Set (Union by Rank & Path Compression)", difficulty:"H", viz:"social", world:"Friend Circles", hook:"Merge circles; ask if two were already one." },
    { id:"15-39", section:"MST & DSU",     title:"Kruskal's Algorithm",        difficulty:"M", viz:"powerline", world:"Building Bridges",    hook:"Cheapest bridges first — but never close a cycle." },
    { id:"15-40", section:"MST & DSU",     title:"Number of Operations to Make Network Connected", difficulty:"M", viz:"social", world:"Rewiring", hook:"Spare cables must cover the component gaps." },
    { id:"15-41", section:"MST & DSU",     title:"Accounts Merge",             difficulty:"H", viz:"social",   world:"Merging Identities",   hook:"Emails are the edges between accounts." },
    { id:"15-42", section:"MST & DSU",     title:"Number of Islands II",       difficulty:"H", viz:"grid",     world:"Rising Land",          hook:"Union-find handles land appearing over time." },
    { id:"15-43", section:"MST & DSU",     title:"Making a Large Island",      difficulty:"H", viz:"grid",     world:"Land Reclamation",     hook:"Size each island once, then test each water cell." },
    { id:"15-44", section:"MST & DSU",     title:"Most Stones Removed",        difficulty:"H", viz:"graphs",   world:"Shared Lines",         hook:"Each component leaves exactly one stone." },

    { id:"15-45", section:"Other",         title:"Bridges in a Graph",         difficulty:"H", viz:"graphs",   world:"Critical Roads",       hook:"Tarjan's: an edge no back edge spans." },
    { id:"15-46", section:"Other",         title:"Articulation Points",        difficulty:"H", viz:"graphs",   world:"Critical Junctions",   hook:"Remove it and the network splits." },
    { id:"15-47", section:"Other",         title:"Strongly Connected Components (Kosaraju)", difficulty:"H", viz:"graphs", world:"Mutual Reachability", hook:"Two passes, the second on the reversed graph." },
  ]),

  S("Step 16", "Dynamic Programming", [
    { id:"16-1",  section:"Intro",        title:"Introduction to DP",          difficulty:"E", viz:"dp",         world:"The Memo Vault",     hook:"Remember the past to conquer the future." },
    { id:"16-2",  section:"1D DP",        title:"Climbing Stairs",             difficulty:"E", viz:"dp",         world:"Climbing Steps",     hook:"Fibonacci wearing a staircase." },
    { id:"16-3",  section:"1D DP",        title:"Frog Jump",                   difficulty:"M", viz:"dp",         world:"Stepping Stones",    hook:"Cost, not count — the first real DP." },
    { id:"16-4",  section:"1D DP",        title:"Frog Jump with K Distances",  difficulty:"M", viz:"dp",         world:"Stepping Stones",    hook:"K choices per state instead of two." },
    { id:"16-5",  section:"1D DP",        title:"Maximum Sum of Non-Adjacent Elements", difficulty:"M", viz:"dp", world:"House Robber",      hook:"Take it and skip one, or skip it." },
    { id:"16-6",  section:"1D DP",        title:"House Robber II (circular)",  difficulty:"M", viz:"dp",         world:"Circular Street",    hook:"Run it twice, excluding one end each time." },

    { id:"16-7",  section:"2D / Grids",   title:"Ninja's Training",            difficulty:"M", viz:"dpgrid",     world:"Daily Schedule",     hook:"State is the day plus yesterday's choice." },
    { id:"16-8",  section:"2D / Grids",   title:"Grid Unique Paths",           difficulty:"M", viz:"dpgrid",     world:"Robot Grid",         hook:"Count every route without listing one." },
    { id:"16-9",  section:"2D / Grids",   title:"Grid Unique Paths II (obstacles)", difficulty:"M", viz:"dpgrid", world:"Robot Grid",        hook:"A blocked cell contributes zero." },
    { id:"16-10", section:"2D / Grids",   title:"Minimum Path Sum in Grid",    difficulty:"M", viz:"dpgrid",     world:"Cheapest Route",     hook:"Each cell takes the cheaper of two predecessors." },
    { id:"16-11", section:"2D / Grids",   title:"Triangle (fixed start, variable end)", difficulty:"M", viz:"dpgrid", world:"Falling Path",   hook:"Build upward from the base." },
    { id:"16-12", section:"2D / Grids",   title:"Minimum/Maximum Falling Path Sum", difficulty:"M", viz:"dpgrid", world:"Falling Path",      hook:"Three predecessors per cell, not two." },
    { id:"16-13", section:"2D / Grids",   title:"Cherry Pickup II (3D DP)",    difficulty:"H", viz:"dpgrid",     world:"Two Robots",         hook:"Two positions in one state." },

    { id:"16-14", section:"Subsequences", title:"Subset Sum Equal to Target",  difficulty:"M", viz:"dpgrid",     world:"Filling a Bag",      hook:"The template every knapsack variant copies." },
    { id:"16-15", section:"Subsequences", title:"Partition Equal Subset Sum",  difficulty:"M", viz:"balance",    world:"Balanced Scales",    hook:"Target is half the total — or it's impossible." },
    { id:"16-16", section:"Subsequences", title:"Partition Set Into Two Subsets With Min Difference", difficulty:"H", viz:"balance", world:"Balanced Scales", hook:"Read the last row for the closest split." },
    { id:"16-17", section:"Subsequences", title:"Count Subsets with Sum K",    difficulty:"H", viz:"dpgrid",     world:"Counting Ways",      hook:"Zeros make the base case subtle." },
    { id:"16-18", section:"Subsequences", title:"Count Partitions with Given Difference", difficulty:"H", viz:"dpgrid", world:"Counting Ways", hook:"Rearranges into a count-subsets problem." },
    { id:"16-19", section:"Subsequences", title:"0/1 Knapsack",                difficulty:"H", viz:"vault",      world:"Limited Hold",       hook:"Take it or leave it — each item once." },
    { id:"16-20", section:"Subsequences", title:"Minimum Coins",               difficulty:"M", viz:"vault",      world:"Cash Drawer",        hook:"Where grabbing the biggest coin first goes wrong." },
    { id:"16-21", section:"Subsequences", title:"Target Sum",                  difficulty:"M", viz:"dpgrid",     world:"Signs and Sums",     hook:"Assigning signs is partitioning in disguise." },
    { id:"16-22", section:"Subsequences", title:"Coin Change II (count ways)", difficulty:"M", viz:"vault",      world:"Cash Drawer",        hook:"Unbounded — stay on the same row." },
    { id:"16-23", section:"Subsequences", title:"Unbounded Knapsack",          difficulty:"M", viz:"vault",      world:"Unlimited Stock",    hook:"The index doesn't advance when you take." },
    { id:"16-24", section:"Subsequences", title:"Rod Cutting Problem",         difficulty:"M", viz:"vault",      world:"Cutting Stock",      hook:"Unbounded knapsack with lengths as weights." },

    { id:"16-25", section:"Strings",      title:"Longest Common Subsequence",  difficulty:"M", viz:"dna",        world:"DNA Alignment",      hook:"Find the sequence two strands share." },
    { id:"16-26", section:"Strings",      title:"Print Longest Common Subsequence", difficulty:"H", viz:"dna",   world:"DNA Alignment",      hook:"Walk the table backwards to recover it." },
    { id:"16-27", section:"Strings",      title:"Longest Common Substring",    difficulty:"M", viz:"dna",        world:"DNA Alignment",      hook:"A mismatch resets to zero, unlike LCS." },
    { id:"16-28", section:"Strings",      title:"Longest Palindromic Subsequence", difficulty:"M", viz:"mirror", world:"Mirror Sequence",    hook:"LCS of the string with its reverse." },
    { id:"16-29", section:"Strings",      title:"Minimum Insertions to Make Palindrome", difficulty:"H", viz:"mirror", world:"Mirror Sequence", hook:"Length minus the longest palindromic subsequence." },
    { id:"16-30", section:"Strings",      title:"Minimum Insertions/Deletions to Convert A to B", difficulty:"M", viz:"dna", world:"Edit Budget", hook:"Everything outside the LCS must go." },
    { id:"16-31", section:"Strings",      title:"Shortest Common Supersequence", difficulty:"H", viz:"dna",      world:"Merged Strand",      hook:"Both strings, sharing the LCS once." },
    { id:"16-32", section:"Strings",      title:"Distinct Subsequences",       difficulty:"H", viz:"dna",        world:"Counting Matches",   hook:"Match or skip — counts, not lengths." },
    { id:"16-33", section:"Strings",      title:"Edit Distance",               difficulty:"H", viz:"dna",        world:"Spell Check",        hook:"How many keystrokes turn one word into another?" },
    { id:"16-34", section:"Strings",      title:"Wildcard Matching",           difficulty:"H", viz:"dna",        world:"Pattern Matching",   hook:"A star can consume nothing, or everything." },

    { id:"16-35", section:"Stocks",       title:"Best Time to Buy and Sell Stock", difficulty:"E", viz:"stockchart", world:"Stock Market",   hook:"Remember the cheapest day behind you." },
    { id:"16-36", section:"Stocks",       title:"Buy and Sell Stock II",       difficulty:"M", viz:"stockchart", world:"Stock Market",       hook:"Every rise is profit when trades are unlimited." },
    { id:"16-37", section:"Stocks",       title:"Buy and Sell Stock III",      difficulty:"H", viz:"stockchart", world:"Stock Market",       hook:"At most two transactions — add a cap to the state." },
    { id:"16-38", section:"Stocks",       title:"Buy and Sell Stock IV",       difficulty:"H", viz:"stockchart", world:"Stock Market",       hook:"Generalise the cap to k." },
    { id:"16-39", section:"Stocks",       title:"Buy and Sell With Cooldown",  difficulty:"M", viz:"stockchart", world:"Stock Market",       hook:"Selling costs you the next day." },
    { id:"16-40", section:"Stocks",       title:"Buy and Sell With Transaction Fee", difficulty:"M", viz:"stockchart", world:"Stock Market", hook:"Subtract the fee once per completed trade." },

    { id:"16-41", section:"LIS",          title:"Longest Increasing Subsequence", difficulty:"M", viz:"mountain", world:"Rising Path",       hook:"The O(n log n) version isn't the actual subsequence." },
    { id:"16-42", section:"LIS",          title:"Print Longest Increasing Subsequence", difficulty:"M", viz:"mountain", world:"Rising Path",  hook:"Track predecessors to recover it." },
    { id:"16-43", section:"LIS",          title:"Largest Divisible Subset",    difficulty:"M", viz:"mountain",   world:"Divisible Chain",    hook:"Sort first, then it's LIS with a divisibility test." },
    { id:"16-44", section:"LIS",          title:"Longest String Chain",        difficulty:"M", viz:"trie",       world:"Word Chain",         hook:"LIS where the order is 'is a predecessor of'." },
    { id:"16-45", section:"LIS",          title:"Longest Bitonic Subsequence", difficulty:"M", viz:"mountain",   world:"Up Then Down",       hook:"LIS forwards plus LIS backwards." },
    { id:"16-46", section:"LIS",          title:"Number of Longest Increasing Subsequences", difficulty:"M", viz:"mountain", world:"Counting Paths", hook:"Carry a count alongside each length." },

    { id:"16-47", section:"Partition",    title:"Matrix Chain Multiplication", difficulty:"H", viz:"dpgrid",     world:"Order of Operations", hook:"Try every split point as the last multiply." },
    { id:"16-48", section:"Partition",    title:"Minimum Cost to Cut the Stick", difficulty:"H", viz:"dpgrid",   world:"Cutting Stock",      hook:"Add the ends and the interval DP appears." },
    { id:"16-49", section:"Partition",    title:"Burst Balloons",              difficulty:"H", viz:"particles",  world:"Bursting Order",     hook:"Think about which balloon bursts last." },
    { id:"16-50", section:"Partition",    title:"Evaluate Boolean Expression to True", difficulty:"H", viz:"circuit", world:"Logic Gates",   hook:"Count true and false ways at every split." },
    { id:"16-51", section:"Partition",    title:"Palindrome Partitioning II",  difficulty:"H", viz:"mirror",     world:"Cutting a String",   hook:"Front partition, with a palindrome precheck." },
    { id:"16-52", section:"Partition",    title:"Partition Array for Maximum Sum", difficulty:"M", viz:"dpgrid",  world:"Chunking",          hook:"Try every chunk length ending here." },

    { id:"16-53", section:"Squares",      title:"Maximal Rectangle",           difficulty:"H", viz:"grid",       world:"Skyline Grid",       hook:"Histogram largest-rectangle, once per row." },
    { id:"16-54", section:"Squares",      title:"Count Square Submatrices with All Ones", difficulty:"M", viz:"grid", world:"Tiling Squares", hook:"Each cell extends the squares ending at it." },
  ]),

  S("Step 17", "Tries", [
    { id:"17-1", section:"Tries", title:"Implement Trie (Insert, Search, StartsWith)", difficulty:"H", viz:"trie",    world:"Prefix Tree",       hook:"Autocomplete without repeating prefixes." },
    { id:"17-2", section:"Tries", title:"Implement Trie II (count prefixes/words)",    difficulty:"M", viz:"trie",    world:"Prefix Tree",       hook:"Counters at every node, not just leaves." },
    { id:"17-3", section:"Tries", title:"Longest Word With All Prefixes",              difficulty:"M", viz:"trie",    world:"Buildable Words",   hook:"Every prefix must itself be a word." },
    { id:"17-4", section:"Tries", title:"Number of Distinct Substrings",               difficulty:"H", viz:"trie",    world:"Counting Substrings", hook:"Every new trie node is a new substring." },
    { id:"17-5", section:"Tries", title:"Maximum XOR of Two Numbers in an Array",      difficulty:"H", viz:"circuit", world:"Bitwise Trie",      hook:"Store bits, then greedily take the opposite branch." },
    { id:"17-6", section:"Tries", title:"Maximum XOR With an Element From Array",      difficulty:"H", viz:"circuit", world:"Bitwise Trie",      hook:"Sort the queries so the trie only grows." },
    { id:"17-7", section:"Tries", title:"Word Search II",                              difficulty:"H", viz:"trie",    world:"Word Grid",         hook:"A trie prunes the grid search enormously." },
  ]),

  S("Step 18", "Strings (Advanced)", [
    { id:"18-1", section:"Advanced", title:"Minimum Number of Bracket Reversals", difficulty:"M", viz:"stackviz", world:"Fixing Brackets",      hook:"Count the unmatched on each side." },
    { id:"18-2", section:"Advanced", title:"Count and Say",                       difficulty:"M", viz:"terminal", world:"Run-Length Speech",    hook:"Each term describes the one before it." },
    { id:"18-3", section:"Advanced", title:"Hashing in Strings (Rolling Hash)",   difficulty:"H", viz:"dna",      world:"Rolling Fingerprint",  hook:"Roll the hash instead of rehashing the window." },
    { id:"18-4", section:"Advanced", title:"Rabin-Karp Substring Search",         difficulty:"H", viz:"dna",      world:"Rolling Fingerprint",  hook:"Hash collisions still need a real comparison." },
    { id:"18-5", section:"Advanced", title:"KMP Algorithm / LPS Array",           difficulty:"H", viz:"dna",      world:"Genetic Sequence",     hook:"Find a pattern without ever re-reading a character." },
    { id:"18-6", section:"Advanced", title:"Shortest Palindrome",                 difficulty:"H", viz:"mirror",   world:"Mirror Prefix",        hook:"The longest palindromic prefix, found by KMP." },
    { id:"18-7", section:"Advanced", title:"Longest Happy Prefix",                difficulty:"H", viz:"dna",      world:"Prefix Equals Suffix", hook:"Exactly what the LPS array computes." },
    { id:"18-8", section:"Advanced", title:"Z-Function",                          difficulty:"H", viz:"dna",      world:"Match Lengths",        hook:"Longest match with the prefix, at every position." },
    { id:"18-9", section:"Advanced", title:"Boyer-Moore (Bad Character Rule)",    difficulty:"H", viz:"dna",      world:"Skipping Ahead",       hook:"Scan the pattern backwards and skip further." },
  ]),
];

export default A2Z_STEPS;
